wakujs/waku

package.json, pnpm-lock.yaml, src/client.ts, src/middleware/rscDev.ts
following https://github.com/facebook/react/pull/26360
=> fix: reply encoding

examples/01_counter/package.json, examples/02_async/package.json, examples/03_promise/package.json, examples/04_callserver/package.json, examples/05_mutation/package.json, examples/06_nesting/package.json, src/builder.ts
we should skip node_modules. for now, it's hard-coded.
=> fix: standalone build

examples/postcss.config.js
Trying to run the 01_counter example straight out of the example folder I got this error message in my terminal
```
[vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')
Plugin: vite:css
File: /Users/tobbe/dev/waku/examples/01_counter/index.html?html-proxy&direct&index=0.css
at getTailwindConfig (/Users/tobbe/dev/waku/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:87:62)
at /Users/tobbe/dev/waku/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:99:92
at /Users/tobbe/dev/waku/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
at plugins (/Users/tobbe/dev/waku/node_modules/tailwindcss/lib/plugin.js:38:63)
at LazyResult.runOnRoot (/Users/tobbe/dev/waku/examples/01_counter/node_modules/postcss/lib/lazy-result.js:339:16)
at …
```
=> Add empty postcss config to make examples runnable

CHANGELOG.md, src/lib/rsc-handler-worker.ts, src/lib/rsc-utils.ts
To support uncommon config just in case.
=> fix: rscPrefix config without trailing slash

CHANGELOG.md, src/lib/builder.ts, src/lib/middleware/rsc/worker-impl.ts
This avoids externalizing modules for rsc transforming.
With this `server-only` doesn't throw on server. (Probably a regression since #21.)
There's one issue though. It doesn't throw when building, but only when running the app.
Thanks to @lubieowoce.
=> fix: react-server condition for libraries

CHANGELOG.md, examples/01_counter/entries.ts, examples/02_async/entries.ts, examples/03_promise/entries.ts, examples/04_callserver/entries.ts, examples/05_mutation/entries.ts, examples/06_nesting/entries.ts, src/lib/builder.ts, src/lib/middleware/rsc.ts, src/lib/middleware/rsc/worker-api.ts, src/lib/middleware/rsc/worker-impl.ts, src/router/server.ts, src/server.ts, website/routes/practices/minimal.tsx, website/routes/practices/router.tsx
It's mostly refactoring, but it's a public api name as well.
It's not breaking if we use `defineEntries`.
=> fix: rename getBuilder to getBuildConfig

CHANGELOG.md, examples/07_router/routes/index.tsx, examples/07_router/src/ErrorBoundary.tsx, examples/07_router/src/index.tsx, src/client.ts, src/lib/middleware/rsc.ts, src/lib/middleware/rsc/utils.ts, src/lib/middleware/rsc/worker-api.ts, src/lib/middleware/rsc/worker-impl.ts, src/router/client.ts, src/router/server.ts
It was 500 previously. Now, if `getEntry` returns `null`, it means 404.
=> feat: support 404 for rsc

package.json
When clone the repo at the **first time**, can not run examples after running pnpm install.
It tells waku: command not found.
If waku link was built in the dir before, it would not warn the error.
Run in mac OS 13.2.1 (22D68), Node v18.16.0
I found the bin property is corrent, but it can't work
I re-clone the repo and update the bin then run pnpm install, it fixed.
=> fix: update bin to fix command not found when run examples

CHANGELOG.md, README.md, package.json, src/lib/builder.ts, src/lib/middleware/rsc/worker-api.ts, src/lib/middleware/rsc/worker-impl.ts, src/node-loader.ts, website/src/routes/docs/installing.tsx
Relates with #79 and #96
It partly reverts the idea in #21.
Closes #44
=> feat: use node-loader again

src/lib/middleware/ssr.ts
Since fetch api will be used both in browser and node runtime in waku, it is better to just use type cast rather than shim it in global.d.ts.
=> fix: readable stream type issue workaround

packages/create-waku/src/cli.ts
Running `npx create-waku` resulting the error,
```
Error: ENOENT: no such file or directory, scandir 'template'
```
Changing the code manually in `node_modules` on my system in the package `create-waku/dist/cli.js` works,
```diff
- const CHOICES = fs.readdirSync("template");
+ const templateRoot = path.join(__dirname, "../template");
+ const CHOICES = fs.readdirSync(templateRoot);
```
Because it checks the template folder in `cwd` on our system rather than in `create-waku` package we have to change this.
=> fix(cli): scan template error

packages/waku/src/cli.ts
When I start multiple services in `/examples`, I notice that the server only uses port 3000. There seems to be a better option, to choose the next port number when the current one is occupied.
=> fix: resolve multiple port occupancy conflict

.github/workflows/cd.yml, .github/workflows/ci.yml, package.json
`packageVersion` is a new built-in API from node.js that could lock the package manager and its version from the top level.
=> chore: lock pnpm version in `package.json`

.github/workflows/ci.yml, examples/01_counter/tsconfig.json, examples/02_async/src/components/App.tsx, examples/02_async/tsconfig.json, examples/02_async/tsconfig.node.json, examples/03_promise/tsconfig.json, examples/04_callserver/tsconfig.json, examples/05_mutation/tsconfig.json, examples/06_nesting/tsconfig.json, examples/07_router/tsconfig.json, examples/07_router/tsconfig.node.json, examples/08_cookies/tsconfig.json, examples/09_cssmodules/tsconfig.json, examples/10_dynamicroute/tsconfig.json, examples/10_dynamicroute/tsconfig.node.json, examples/11_form/tsconfig.json, package.json, packages/create-waku/src/cli.ts, packages/create-waku/tsconfig.json, packages/waku/package.json, packages/waku/src/client.ts, packages/waku/src/router/client.ts, packages/waku/src/types.d.ts, packages/waku/tsconfig.build.json, packages/waku/tsconfig.json, packages/website/tsconfig.json, tsconfig.e2e.json, tsconfig.json
Add top-level ts config that includes all submodules, which restricts the type and isolated type context. If some files are missing or wrong-typed, it will throw the error.
=> refactor: use tsconfig monorepo

packages/create-waku/package.json, packages/create-waku/src/cli.ts, packages/create-waku/tsconfig.json, pnpm-lock.yaml
https://github.com/dai-shi/waku/pull/132#discussion_r1370887758
=> refactor: remove esbuild

.gitignore
After 303b33f7fd61f91ea2b2a407d8711c208d22e289, tsbuildinfo will be emitted in the base dir
=> chore: ignore tsbuild info files

CHANGELOG.md, packages/waku/src/lib/middleware/rsc/worker-api.ts, packages/waku/src/lib/middleware/rsc/worker-impl.ts
It looks like `--experimental-loader` doesn't work for Worker in Node 20.
https://github.com/nodejs/node/issues/47747
=> fix: support node 20

CHANGELOG.md, packages/waku/src/config.ts, packages/waku/src/lib/builder.ts, packages/waku/src/lib/config.ts, packages/waku/src/lib/middleware/rsc.ts
Just a minor change. Technically breaking, but it's not used in the repo.
=> rename rscPrefix to rscPath

packages/create-waku/package.json, packages/waku/package.json
`.tsbuildinfo` is a cache file, if you didn't remove it correctly. tsc will treat the output still remain in this case.
Fixes: https://github.com/dai-shi/waku/issues/167
Fixes: https://github.com/dai-shi/waku/issues/168
=> chore: fix build output disappear

packages/waku/src/client.ts, packages/waku/src/lib/middleware/rsc/ssr.ts, packages/waku/src/lib/middleware/rsc/utils.ts, packages/waku/src/lib/middleware/rsc/worker-impl.ts, packages/waku/src/types.d.ts, packages/website/src/main.tsx
Continuing from #190.
This converts mainly `ssr.ts`.
=> refactor: use web stream internally (step 2)

examples/06_nesting/src/components/Counter.tsx, packages/waku/package.json, packages/waku/src/lib/middleware/rsc/utils.ts, packages/waku/src/lib/middleware/rsc/worker-impl.ts, packages/waku/src/types.d.ts, pnpm-lock.yaml
Previous PRs: #190, #196
This converts mainly `worker-impl.ts`.
=> refactor: use web stream internally (step 3)

examples/03_promise/src/components/Counter.tsx, examples/03_promise/tsconfig.json
This will fix the hydration issue. Not sure if this is correct
Fixes: https://github.com/dai-shi/waku/issues/202
=> fix: hydration error on promise example

packages/waku/src/lib/builder.ts, packages/waku/src/lib/middleware/rsc.ts, packages/waku/src/lib/middleware/rsc/ssr.ts, packages/waku/src/lib/middleware/rsc/utils.ts, packages/waku/src/lib/middleware/rsc/worker-api.ts, packages/waku/src/lib/middleware/rsc/worker-impl.ts, packages/waku/src/lib/rsc/renderer.ts, packages/waku/src/lib/utils/form.ts
=> Refactor: use Worker only in DEV

packages/waku/src/lib/plugins/vite-plugin-nonjs-resolve.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
The error happens when we run waku build normally (outside of this repo).
I wish there's a way to reproduce the behavior within the repo...
=> fix: getClientId error

packages/waku/src/lib/rsc/worker-api.ts, packages/waku/src/lib/rsc/worker-impl.ts
https://nodejs.org/dist/latest-v20.x/docs/api/module.html#moduleregisterspecifier-parenturl-options
It turns out not all Node 20 has `register`.
=> fix: better detection of module register

package.json, packages/waku/src/cli.ts, packages/waku/src/dev.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/builder/output-vercel.ts
and refactor builder.ts a little bit.
=> fix: vercel output

README.md, packages/waku/src/cli.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/builder/output-cloudflare.ts, packages/waku/src/lib/rsc/worker-api.ts
It's just minimal and for testing.
=> feat: output cloudflare

README.md
Hi. I'm interested in waku. So I've forked and played with some examples.
When I install the dependencies using `npm`, it had an error below:
So I revised README.md [here](https://github.com/dai-shi/waku?tab=readme-ov-file#how-to-try-it-1) (Need to install dependencies using `pnpm`)
=> docs: npm install to pnpm install

packages/waku/src/lib/middleware/hono-utils.ts
=> fix: controller is already closed error

package.json
even #313 didn't work.
The problem is generated html that only happens Vercel production build. It doesn't happen with Vercel preview build.
[index.html.zip](https://github.com/dai-shi/waku/files/13767782/index.html.zip)
Assuming it's static only problem, disabling it for now.
=> website: disable --with-vercel-static for now

packages/waku/src/lib/handlers/dev-worker-api.ts, packages/waku/src/lib/handlers/dev-worker-impl.ts, packages/waku/src/lib/handlers/types.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-delegate.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-reload.ts, packages/website/src/style.css
In `handleHotUpdate` we re-inject/re-transform the module and send an update to the hmr listener (`import.meta.hot.on('module', ...)`). 
To avoid multiple hmr script tags, we add an `id` to the `TransformResult` (now `ModuleImportResult`) so we can identify any script tag with the same `waku-module-id` so we remove it from the DOM and replace it with a new one that has the new content.
=> feat: css hmr

packages/waku/src/lib/handlers/dev-worker-api.ts, packages/waku/src/lib/handlers/dev-worker-impl.ts, packages/waku/src/lib/renderers/html-renderer.ts
Resolves #308 
We implemented our messaging method, but streams are already transferrable between the worker and the main thread. The only issue is that the types are not supporting them although the implementation does support them, that's why I used `as unknown as TransferListItem`
=> chore(worker-api/impl): pass stream to parent

packages/waku/src/lib/handlers/handler-dev.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/website/package.json, packages/website/src/components/modal.tsx, packages/website/vite.config.ts
=> chore: avoid website issues

packages/waku/package.json
There was a reason to have CJS, but I think the need is already gone. So, let's try.
=> waku: remove cjs build

packages/waku/src/cli.ts, packages/waku/src/lib/handlers/dev-worker-api.ts, packages/waku/src/lib/handlers/dev-worker-impl.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-env.ts
While we support non-Node environment, many use cases are with Node. We support using `process.env` on the server with Node, and also `process.env.WAKU_PUBLIC_*` for client bundling in addition to `import.meta.env.WAKU_PUBLIC_*` which is the recommended way.
=> Node compatible `process.env`

packages/waku/src/lib/handlers/handler-dev.ts, packages/waku/src/lib/renderers/html-renderer.ts, packages/website/package.json, packages/website/src/components/menu.tsx, packages/website/vite.config.ts, pnpm-lock.yaml
=> fix(website): dev experience and use Link

examples/12_css/package.json, examples/12_css/src/components/App.css, examples/12_css/src/components/Banner.tsx, examples/12_css/vite.config.ts, pnpm-lock.yaml
`vite-plugin-stylex-dev` has more features than `vite-plugin-stylex`, and then `vite-plugin-stylex-dev` can convert most of scense. Such as `path alias` and etc. And it can work well with vite’s internal css plugin. So i think using `vite-plugin-stylex-dev` is better.
=> chore: switch `vite-plugin-stylex`  to `vite-plugin-stylex-dev`

examples/01_counter/tsconfig.json, examples/02_async/tsconfig.json, examples/03_promise/tsconfig.json, examples/04_callserver/tsconfig.json, examples/05_mutation/tsconfig.json, examples/06_nesting/tsconfig.json, examples/07_router/tsconfig.json, examples/08_cookies/package.json, examples/08_cookies/tsconfig.json, examples/09_cssmodules/tsconfig.json, examples/10_dynamicroute/tsconfig.json, examples/10_dynamicroute/tsconfig.node.json, examples/11_form/tsconfig.json, examples/12_css/tsconfig.json, examples/12_css/tsconfig.node.json, examples/13_path-alias/tsconfig.json, examples/13_path-alias/tsconfig.node.json, pnpm-lock.yaml, tsconfig.json
It might be ok to remove this. Don't be too strict with the user.
Also remove examples from monorepo. E2e smoke check will build the project and check the type
=> fix: reduce unnecessary ts config from examples

e2e/examples-smoke.spec.ts, e2e/rsc-basic.spec.ts, e2e/rsc-router.spec.ts, e2e/ssr-basic.spec.ts, packages/waku/src/lib/handlers/dev-worker-impl.ts, packages/waku/src/lib/handlers/handler-dev.ts
For a long time, we have `Re-optimizing dependencies because vite config has changed` message and not sure how to fix.
Reading the vite code, we can work it around.
https://github.com/vitejs/vite/blob/ed56d96cec8fd3b9b6dae88d5511e386177e6d5c/packages/vite/src/node/optimizer/index.ts#L1218
Note that it depends on the vite internals and can be fragile.
=> fix: avoid vite config has changed

e2e/ssr-basic.spec.ts, packages/waku/src/lib/handlers/dev-worker-api.ts, packages/waku/src/lib/handlers/dev-worker-impl.ts, packages/waku/src/lib/handlers/handler-dev.ts, packages/waku/src/lib/handlers/types.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-delegate.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
=> DEV: loading indicator to mitigate FOUC

packages/website/postcss.config.js
fixes [prop mismatch error with ssr](https://github.com/dai-shi/waku/pull/364#issuecomment-1888505712) in #344 
In transformIndexHtml, waku will transform and return the result to the browser! In this process, vite will apply its transformation which postcss/autoprefixer is part of. Autoprefixer will add the -moz- pseudo-class. 
A better solution will be an upstream one, in the `bright` package which should use autoprefixer [control comments](https://github.com/postcss/autoprefixer?tab=readme-ov-file#control-comments) and disable the prefixing to the inline CSS part that React will process. 
With this PR's solution, what we do is just disable the prefixing for the whole website.
```html
React stream: 
<style>
[data-bright-theme] ::selection { background-color: var(--selection-background) …
```
=> fix(website): prop mismatch error with ssr by turning off autoprefixing

packages/waku/src/lib/plugins/vite-plugin-rsc-delegate.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts, pnpm-lock.yaml
Resolves #439 
The #427 PR treated all the CSS files the same way. CSS modules in vite act like real scripts and there's no way to ssr transform them and get the actual CSS, instead, we get the CSS keys that we should use in our general files.
What I do in this PR is revert the script injecting way of loading CSS, only for CSS modules, and for fixing FOUC, I make that script blocking, which is not ideal at all, but works for now. 
I see right now also that hmr with CSS modules in server components is broken since I guess hmr does not work well in server components.
=> fix: css modules 

examples/05_actions/src/components/App.tsx, examples/05_actions/src/components/Counter.tsx, packages/waku/src/lib/handlers/handler-dev.ts
Resolves #434 
TIL: 
```ts
export * from 'url'
```
does not re-export the `default` export.
=> fix: client components default exports

packages/waku/src/config.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/config.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/src/lib/renderers/html-renderer.ts, packages/waku/src/lib/utils/node-fs.ts
=> build ssr bundle separately

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/handlers/dev-worker-impl.ts, packages/waku/src/lib/handlers/handler-dev.ts
There's an issue with cloudflare deploy since #457.
As it turns, it's targeting `node`.
https://vitejs.dev/config/ssr-options.html#ssr-target
This should fix.
=> fix build for RSC and SSR

e2e/fixtures/ssr-target-bundle/README.md, e2e/fixtures/ssr-target-bundle/package.json, e2e/fixtures/ssr-target-bundle/src/components/App.tsx, e2e/fixtures/ssr-target-bundle/src/components/Textarea.tsx, e2e/fixtures/ssr-target-bundle/src/entries.tsx, e2e/fixtures/ssr-target-bundle/src/main.tsx, e2e/fixtures/ssr-target-bundle/tsconfig.json, e2e/ssr-target-bundle.spec.ts, pnpm-lock.yaml, tsconfig.e2e.json
As requested #481 this is a simpler Version which does not use screen shots to test results.
Choosing the right code based on the `export` section of the `react-textarea-autosize` module based on the backend server deployment target ('node' | 'webworker') and the client browser. No browser only code should be bundled with server only code.
You can simple test this fixture by setting `isNodeCompatible` to false
=> feat: Test bundling packages which provide environment depended code parts

packages/waku/src/lib/handlers/handler-dev.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts, packages/waku/src/lib/renderers/html-renderer.ts
Partially resolves #344 
When refreshing a waku page (website), the hydration failed and as result, hmr would not work. 
The reason behind the failure, is that for the next refreshes, the `/main.tsx` file is optimized and warm so it gets resolved before the `<body>` is getting streamed to the browser since it was in the `<head>` and that loads before the `<body>`, what that mean is the `document.body` would be undefined during the hydration and React would throw an error since that is undefined. One solution was to restart the server so we get `/main.tsx` cold again.
What this PR does is that it puts the script of `/main.tsx` in the body so it gets resolved after the body is being streamed and as a result, document.body would be never be `undefined`. 
This also fixed the hmr issue after …
=> fix: document body undefined

packages/waku/src/lib/builder/serve-aws-lambda.ts
This change allows to handle the differences of bundling the deployment ZIP for the serverless framework and the AWS CDK.
=> fix: add option to define the root folder of a lambda deployment.

packages/waku/src/lib/builder/output-partykit.ts, packages/waku/src/lib/builder/serve-partykit.ts
This serves `404.html`, if available in `/public`, for unmatched requests.
(This also adds a bugfix for the generated `partykit.json` config file.)
=> feat: `--with-partykit`, 404 responses

examples/01_template/tsconfig.json, examples/02_demo/tsconfig.json, examples/14_react-tweet/tsconfig.json
There is no support for path alias unless you add vite plugin
=> fix: remove paths in examples

packages/waku/src/router/client.ts
Link is always appends `?` to the end of the url even if there are no search params.
=> fix: Do not process empty search params to avoid redundant question mark

packages/waku/src/lib/handlers/handler-dev.ts, packages/waku/src/lib/middleware/dev-server.ts, packages/waku/src/lib/middleware/ssr.ts, packages/waku/src/lib/middleware/types.ts
There was a regression in #534.
I shouldn't have deleted `willBeHandledByVite`.
=> fix(ssr): catch-all route

packages/waku/src/cli.ts
This is something I forgot to fix in #565.
=> fix(cli): start cmd should not read config

e2e/fixtures/rsc-basic/waku.config.ts, e2e/fixtures/rsc-router/waku.config.ts, examples/08_cookies/waku.config.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/config.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/server.ts
#572 depends on Node.js even in production build, which isn't ideal.
=> fix: fs-router for non-Node envs

examples/05_actions/src/components/funcs.ts
https://github.com/dai-shi/waku/issues/576#issuecomment-1985448959
just to make sure it works in this example.
=> chore(examples): add getContext in 05_actions

examples/05_actions/src/components/App.tsx, examples/05_actions/src/components/funcs.ts, examples/08_cookies/src/components/App.tsx, examples/08_cookies/waku.config.ts, packages/waku/src/lib/builder/output-cloudflare.ts, packages/waku/src/lib/renderers/html-renderer.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/server.ts
close #586 
It was my misunderstanding that `cache` does something magical behind the scene, but it uses ALS under the hood.
=> fix: use AsyncLocalStorage for getContext

packages/waku/src/client.ts, packages/waku/src/router/client.ts, packages/waku/src/router/common.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/server.ts
`rerender` is from `waku/server`.
`redirect` is from `waku/router/server`.
It's confusing because `input` and `pathname` look similar with current router implementation, but it might be very different in the future.
=> feat(router): unstable_redirect

packages/waku/src/lib/renderers/html-renderer.ts
Resolves #611 
Apparently, the `./router/client.js?v=a3348fd2` query occurs in monorepos for non `/@fs/` paths.
=> fix: split any filepath by `?`

packages/create-waku/package.json, packages/create-waku/src/helpers/example-option.ts, packages/create-waku/src/helpers/install-template.ts, packages/create-waku/src/index.ts
I had thought it would be nice to have a single `--example` option, but changed my mind. This introduces `--choose` option again.
https://github.com/dai-shi/waku/discussions/315#discussioncomment-8990718
closes #625
along with #641
=> feat(create-waku): recover choose option

examples/07_router/src/entries.tsx, packages/waku/src/main.ts
we need to export js code not only types.
=> fix: createPages type

.github/workflows/ci.yml
For the minimal versions described in "engines".
=> chore(ci): use precise node versions

packages/waku/src/lib/builder/build.ts
=> fix: No styles in client components in PRD

packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-private.ts, packages/waku/src/lib/renderers/dev-worker-impl.ts
Resolves #592 
We did not react to changes in the private dir. 
Since we're sure they're server only, let's treat them as rsc updates, so the changes get reflected on the client.
=> fix: private dir hmr

packages/waku/src/router/fs-router.ts
The current `fs-router` regex, `/(^|\/|\\)_([^/]+)_(\/|\\|\.)/g`, which is ran during build only replaces the first occurrence of underscores in scenarios where multiple underscore-surrounded segments are separated by single slashes. For example, in the string "app/\_propertyId\_/\_surveyPartKey\_.js", only \_propertyId\_ was being replaced, but \_surveyPartKey\_ was left unchanged due to the / being consumed during the first match.
This can easily be checked by running the following code:
```
const file = "app/_propertyId_/_surveyPartKey_.js";
console.log(file.replace(/(^|\/|\\)_([^/]+)_(\/|\\|\.)/g, '$1[$2]$3'));
// app/[propertyId]/_surveyPartKey_.js
```
The regex has been updated to `/(?<=^|\/|\\)_([^/]+)_(?=\/|\\|\.)/g`. This uses positive lookbehind (`?<=^|\/|\\`) and lookahead …
=> fix(waku/router): regex in file replacement to correctly handle all matches (fs-router)

packages/waku/src/lib/builder/output-vercel.ts
Vercel changed their default nodejs version to 20, waku will throw error when deploy to vercel if it's 18
=> fix: default nodejs runtime to 20

packages/waku/package.json, packages/waku/src/internals.ts
=> feat: expose internals

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
Solve https://github.com/dai-shi/waku/issues/649.
I did some research based on https://github.com/dai-shi/waku/pull/674. The root cause is that css path in html missing / so that when brower try to join the real path, it will use the current path instead of root path.
=> fix: non js assets path should add config.basePath to be relative to root path

e2e/multi-platform.spec.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
Solve https://github.com/dai-shi/waku/issues/700
The bug was introduced in https://github.com/dai-shi/waku/pull/682, the reason is that the logic of https://github.com/dai-shi/waku/pull/682/files#diff-6de2cc9d9f6423e3f4faa0cb1a6200112f1bc057af0db1a9362fe6117c51d18aR79-R82 was adjusted.
I think the logic now assmues the entry file is endsWith .jsx while while the dynamic import in serve-vercel.js is endsWith .js
I am not so sure it is a correct way to remove .js extension, but I added the dry run testing, maybe it can help.
=> fix: build target for vercel will throw error

packages/waku/src/client.ts
=> refactor waku/client (technically breaking)

packages/create-waku/src/helpers/example-option.ts
**Current Behaviour:**
```bash
pnpm start --example https://www.github.com/dai-shi/waku/tree/main/examples/02_template_js                                                                                                                 
> create-waku@0.9.2-alpha.0 start /Users/joelmathew/WebProjects/waku-dev/waku/packages/create-waku
> node ./dist/index.js "--example" "https://www.github.com/dai-shi/waku/tree/main/examples/02_template_js"
Invalid URL: "https://www.github.com/dai-shi/waku/tree/main/examples/02_template_js". Only GitHub repositories are supported. Please use a GitHub URL and try again.
```
The url is a valid GitHub url which should be accepted by the `create-waku` utility. This pr should fix this behaviour.
=> fix (create-waku): example GitHub urls can contain `www` too

packages/waku/src/lib/middleware/dev-server.ts, packages/waku/src/lib/plugins/patch-react-refresh.ts
I removed it in #713, because all tests pass without it, but it actually broke example 20,21,22.
I'm not sure why smoke tests didn't catch it.
=> fix: patch-react-refresh

packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/lib/renderers/utils.ts
We use the following naming convention to avoid collisions (best effort).
- For `globalThis`, use `__WAKU_SNAKE_CASE__`
- For others, use `__waku_camelCalse`
=> refactor: naming convention for globals

packages/waku/src/lib/middleware/rsc.ts, packages/waku/src/lib/middleware/ssr.ts, packages/waku/src/lib/renderers/dev-worker-impl.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/types.d.ts
The main logic is `ctx.res.body = stringToStream(`${err}`);`
Cleanup response stream when it raises an error because it's locked by react (how to release it?) otherwise hono server will crash
=> fix: do not crash whole server when error

packages/waku/src/cli.ts
`runStart` wasn't use values from `wake.config.ts`
=> load config for start command

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/dev-server.ts
This `workerd` condition was originally required for the worker thread (not because of the worker thread, but of `server.edge`), and for consistency, the same config existed in build.ts.
Now, as we removed the worker thread in https://github.com/dai-shi/waku/pull/762, I'm confident of removing it too.
cc @himself65
=> chore: eliminate workerd condition

packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
Fix some RSC case, will fix https://github.com/dai-shi/waku/pull/745. In the future, I will migrate the logic to https://github.com/himself65/react-server and keep same output
Some issues still happening:
1. `export default async function () {"use server"}` cannot be RSCA
2. `export function a() { "use server" }` should throw error, because it's not async
=> fix: server action cases

e2e/fixtures/ssr-catch-error/package.json, e2e/fixtures/ssr-catch-error/src/components/client-layout.tsx, e2e/fixtures/ssr-catch-error/src/middleware/validator.ts, e2e/fixtures/ssr-catch-error/src/pages/_layout.tsx, e2e/fixtures/ssr-catch-error/src/pages/index.tsx, e2e/fixtures/ssr-catch-error/src/pages/invalid.tsx, e2e/fixtures/ssr-catch-error/tsconfig.json, e2e/fixtures/ssr-catch-error/waku.config.ts, e2e/ssr-catch-error.spec.ts, pnpm-lock.yaml, tsconfig.e2e.json
It covers #696 and #741.
The test aims at how to implement auth features on the app side.
Considerations:
1. Our client router has to handle 4xx errors that the server responds
2. Middleware can be a validator to respond to 200 or 4xx status on requests 
I'm so glad to send my first PR to Waku, thank you!
=> test: catch an error in client router

packages/waku/src/cli.ts, packages/waku/src/lib/hono/runner.ts
This fixes the issue for me mentioned in #644 where an empty 200 status response is returned instead of a 404 error page.
I found the RSC middleware doesn't run in that case so the ctx.res is never set. I added a fallback to move the hono res.body to the ctx.body if the ctx.body is empty. I assume that won't be a breaking change but 🤷.
=> fix: Hono runner 404 response

README.md, packages/waku/src/router/client.ts, packages/waku/src/router/common.ts, packages/waku/src/router/define-router.ts
#746 revealed that `URLSearchParams` doesn't work.
(In the near future, I will also rework on fetchRSC to eliminate it.)
=> breaking(router): string query

README.md
Warning and fix at build time for static deploy when 'dynamic' is set in the `getConfig`
fixes #804
=> docs: inform static users about the getConfig call

.gitignore
Feel free to just close this if there's a preference to not have this. 
My motivation for adding this is just that with [fnm](https://github.com/Schniz/fnm) (and other node version managers) - they look for this file or .nvmrc to automatically set the node version. Adding this would make it more convenient to swap between different projects that use different node versions.
I chose 20.8.0 because it is enforced in the `packages/waku/package.json` engines field.
=> chore: add nvmrc and node-version to gitignore

packages/waku/src/lib/utils/path.ts, packages/waku/src/router/create-pages.ts, packages/waku/tests/create-pages.test.ts
What I have focused on so far: 
- Removing unnecessary creation of arrays for loops (using iterability of maps)
- jsdoc for functions that I am reading through to understand in the router
- moved some of the types around
- Not sure how I feel about this yet... if splitting up the logic for each of these entry points ends up working out, it will be nice to have these types re-used for that. Otherwise, I will revert that part. (CreatePageStaticWithoutSlug & CreatePageStaticWithSlug)
Notes:
I think I will be adding some more docs and re-organizing a bit more before calling this PR ready.
I am interested to hear opinions and thoughts on the changes so far though, if any.
=> refactor(router): style/performance tweaks to logic and jsdoc added

packages/waku/src/client.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/rsc.ts, packages/waku/src/lib/middleware/ssr.ts, packages/waku/src/lib/renderers/html-renderer.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/lib/renderers/utils.ts, packages/waku/src/router/client.ts, packages/waku/src/router/common.ts, packages/waku/src/router/define-router.ts, packages/waku/src/server.ts
Related previous PR: #799
- Previously, it distinguish whether it's RSC or RSF (server actions) with HTTP method. Now, it's distinguished with path.
- Both RSC and RSF accept GET and POST.
- RSC no longer uses `URLSearchParams` but just any `params`.
=> feat: redesign RSC protocol without URLSearchParams

packages/waku/src/router/client.ts, packages/waku/src/router/common.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts, packages/waku/tests/create-pages.test.ts
`shouldSkip` was trying to be more flexible, but it's hardly understandable.
Replacing with `componentConfig` for now and let's see how it could be in the future.
=> refactor(router): replace shouldSkip with componentConfig

examples/13_path-alias/src/components/App.tsx, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/middleware/rsc.ts, packages/waku/src/lib/middleware/ssr.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-env.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/server.ts
using module variable instead of global variable. Now, possible without any workers.
=> refactor: getEnv

packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts, packages/waku/src/lib/renderers/rsc-renderer.ts
oh, boy, this is huge.
There must be huge room for improvement with `vite-plugin-rsc-rsdw.ts`. We should never use `import` on the server in PRD.
=> fix: load module for actions

packages/waku/src/lib/renderers/html-renderer.ts
In my testing I discovered that `react` and `react-dom-server-webpack/client.edge` could be imported using regular imports. No need to have a local build of those and import that build.
=> html-renderer: Simplify module loading for react

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/renderers/html-renderer.ts
#851 was incomplete. This should cover more edge cases. (Though, it's suboptimal, as it calls `getSsrConfig` twice.)
=> fix(build): better index html generation

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/renderers/rsc-renderer.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/server.ts, packages/waku/tests/create-pages.test.ts
=> feat(build): introduce buildData in platformObject

packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/renderers/html-renderer.ts
Fix #863 
We can't reproduce the error with current e2e tests. It needs standalone tests + SSR.
=> fix(dev): import local node_modules with SSR

tsconfig.json
This results in the ts preview of vscode not truncating the hovered information of a type or error. Helpful for inspecting long types.
Follow up to: https://github.com/dai-shi/waku/pull/854#issuecomment-2336516245
=> chore: add noErrorTruncation to the base tsconfig.json

packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
This fixes cloudflare static vs dynamic routing for the home index page. But there are likely more bugs with the _routes.json when trying to nest a dynamic route under a static route path. By using _routes.json, we can route static html files directly off Cloudflare's CDN and not incur any worker function changes. But we need to make sure it only matches the static html routes.
Right now, it is doing a very basic walk of the public output dir to generate a _routes.json. We need to generate a more accurate list of exclude patterns. I am opening this PR as a draft until I can complete this. Fixes #869
=> fix: cloudflare routing 404

docs/create-pages.mdx, e2e/fixtures/render-type/src/entries.tsx, examples/07_router/src/entries.tsx, packages/waku/package.json, packages/waku/src/router/base-types.ts, packages/waku/src/router/client.ts, packages/waku/src/router/create-pages-utils/inferred-path-types.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/router/util-types.ts, packages/waku/tests/create-pages.test.ts
Currently this changeset gets `createPages` ready to return an inferred type for each response of `createPage`
TODO:
=> feat: infer types for waku router

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
This (along with the previous #874) resolves the issue in #871. The build config was being written to the wrong location for cloudflare pages This PR exports a function from the build module that appends the build config to the given entries file location. It uses a new unstable build config state variable (`unstable_buildConfigSave`) to track whether or not the build config has be saved to the entries file. This allows the cloudflare deploy plugin to write the build config into the worker function directory instead of the root.
We could merge #879 and then I can edit the base branch to main and continue with this PR. Or however you want to handle it. Thank you!
=> fix(deploy): move saving the build config to deploy plugins

packages/waku/src/cli.ts, packages/waku/src/lib/hono/runner.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/unstable_hono.ts
Instead of #852 and #884, let's use Hono's `getContext` instead.
=> feat(hono): enable context storage

examples/08_cookies/package.json, examples/08_cookies/src/components/App.tsx, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/dev-server-impl.ts, pnpm-lock.yaml
=> fix(hono): getContext for DEV&PRD

docs/guides/cloudflare.mdx
Here is a guide with my current understanding of how to run develop and deploy Waku for Cloudflare Pages in the next release that includes the unstable API to access the Hono context.
=> feat(docs): Adding a guide for cloudflare

package.json, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/unstable_hono.ts
#891 and #894 weren't working correctly with deploys.
=> fix(hono): import hono/context-storage directly

examples/12_css/vite.config.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/lib/plugins/vite-plugin-nonjs-resolve.ts
there was a huge misunderstanding.
=> fix: nonjs-resolve plugin

package.json, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts
Based on #882, this fixes some plugins
- Vercel
- Netlify (Found an issue: #909)
- Deno (Found an issue: #908)
=> fix: deployment plugins

README.md, docs/builder/aws-lambda.mdx, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts
adds streaming by using [`streamHandle`](https://hono.dev/docs/getting-started/aws-lambda#lambda-response-streaming) from Hono.
To switch the handler use the environment variable `DEPLOY_AWS_LAMBDA_STREAMING=true`:
```sh
DEPLOY_AWS_LAMBDA_STREAMING=true pnpm build --with-aws-lambda
```
=> feat: deploy aws / add streaming

packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/unstable_hono.ts
re: https://github.com/dai-shi/waku/pull/882#issuecomment-2378365279
Applies the same fix used for handling hono/context-storage with aws builds.
=> Update cloudflare with hono/context-storage external build fix

docs/guides/cloudflare.mdx, examples/08_cookies/src/components/App.tsx, packages/waku/src/cli.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/hono/runner.ts, packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/unstable_hono.ts
at least for now. this reverts #891 and re-introduce #852 and #884.
https://github.com/dai-shi/waku/pull/911#issuecomment-2380439350
=> prefer getHonoContext to hono/context-storage

packages/waku/src/cli.ts, packages/waku/src/lib/builder/serve-partykit.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts
We can omit `'*'` in `app.use()`.
https://github.com/honojs/hono/blob/f1ec415be03784ab8c321577cf35005afd3bea09/src/hono-base.ts#L157-L164
=> refactor: hono app.use usage

examples/25_weave_render/package.json, examples/25_weave_render/src/components/BarLayout.tsx, examples/25_weave_render/src/components/BarPage.tsx, examples/25_weave_render/src/components/Counter.tsx, examples/25_weave_render/src/components/FooLayout.tsx, examples/25_weave_render/src/components/FooPage.tsx, examples/25_weave_render/src/components/HomeLayout.tsx, examples/25_weave_render/src/components/HomePage.tsx, examples/25_weave_render/src/components/NestedBarLayout.tsx, examples/25_weave_render/src/entries.tsx, examples/25_weave_render/src/main.tsx, examples/25_weave_render/src/styles.css, examples/25_weave_render/tsconfig.json, pnpm-lock.yaml
you can see the time change as navigating the site which shows that the layout is indeed dynamic
The rest of the home page stays unchanged and can be cached
Example for #885
=> docs: add example of dynamic layout with static page

examples/07_router/src/components/Counter.tsx, examples/07_router/src/components/funcs.ts, packages/waku/src/router/client.ts, packages/waku/src/router/common.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/server.ts
https://github.com/dai-shi/waku/discussions/927#discussioncomment-10825901
=> fix: rename unstable_redirect and add example

packages/waku/src/cli.ts, packages/waku/src/config.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts
Update `unstable_honoEnhancer` to accept an async function to support dynamic imports.
Update `unstable_honoEnhancer` to pass in the Hono app and the `serveWaku` Hono middleware handler.
Load waku config and invoke `unstable_honoEnhancer` in cloudflare build. If this looks good, we should all this too all of the deploy options.
With these changes, I am able to update my waku.config.ts to this in my Cloudflare Pages project: 
```ts
import type { Hono, MiddlewareHandler } from "hono";
import type { Config, unstable_HonoEnhancer } from "waku/config";
const addApiRoutes = (app: Hono) => {
app.get("/api/hello", (c) => {
return c.json({ hello: "world" });
});
return app;
};
// @ts-expect-error TODO figure out the right way to cast types here
const wakuConfig: Config = {
...(import.meta.env && …
```
=> feat: Add hono enhancer to cloudflare and aws lambda

packages/create-waku/package.json, pnpm-lock.yaml
`@vercel/ncc@0.38.2` seems to break create-waku's `notifyUpdate`.
Here's the error log:
```
TypeError: undefined is not a function
at notifyUpdate (file:///.../node_modules/create-waku/dist/index.js:30:110825)
```
@himself65 @ojj1123 do you think it's fixable?
In the meantime, let's downgrade `ncc`.
=> fix(create-waku): downgrade ncc

packages/waku/src/client.ts, packages/waku/src/lib/middleware/rsc.ts, packages/waku/src/lib/renderers/rsc-renderer.ts
Previously, we used GET with a header, because the header can accept larger string.
But, for larger string, we should use POST anyway, so introducing a new convention `URLSearchParams`. This is still experimental and should be revisited before v1. (Basically, review Next.js's API and re-consider.)
=> experimental GET support

examples/03_demo/tsconfig.json, examples/04_cssmodules/src/types.d.ts, examples/43_weave-render/src/components/BarLayout.tsx, examples/43_weave-render/src/components/HomeLayout.tsx, package.json
LIMITATION: It depends on `find` and doesn't run on windows.
=> chore: run tsc on examples

.gitignore, packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts, packages/waku/src/router/base-types.ts, packages/waku/src/router/create-pages-utils/inferred-path-types.ts, packages/waku/tests/vite-plugin-fs-router-typegen.test.ts
This moves the generation from fs-router types off of `createPages`
Happy to move things around or update examples as needed, but I think this solution simplifies our current uses nicely
=> feat: regenerate fs-router types

packages/create-waku/package.json, packages/create-waku/tsup.config.ts, pnpm-lock.yaml
It looks like a bundler is needed for helping to minify the published code and transpile from typescript.
I've had a good personal experience with tsup and I saw @himself65 mention it, so figured I'd make this PR to help :)
Closes #973
=> refactor: move from ncc to tsup for create-waku

docs/create-pages.mdx
Update create-pages.mdx for documenting the `createRoot` function for supporting customization of the top level tags.
=> docs: update create-pages docs for root

packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
It fails in StackBlitz as `@swc/was` will be used.
=> fix(plugin/fs-router-typegen): use swc.parseSync instead of parseFileSync

packages/create-waku/src/index.ts, packages/create-waku/tsup.config.ts
follow up to this: https://github.com/dai-shi/waku/pull/974#issuecomment-2423476651
=> fix: remove createRequire for package json

packages/create-waku/src/index.ts
fix for https://github.com/dai-shi/waku/pull/978#issuecomment-2425461081
Also fixed an issue where the default folder name was not showing on conflict
=> fix: issues with cli reading from package.json

README.md, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
=> Switch from Cloudflare Pages to Workers with Static Assets

examples/21_create-pages/src/components/NestedBazPage.tsx, examples/21_create-pages/src/entries.tsx, examples/21_create-pages/src/main.tsx, packages/waku/src/main.react-server.ts, packages/waku/src/main.ts, packages/waku/src/router/client.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/server.ts
This adds a new version of `createPages` to use `new_defineRouter` as `new_createPages`
=> feat: new create pages to use new defineRouter

examples/32_minimal_js/src/entries.jsx, examples/32_minimal_js/waku.config.ts, examples/33_promise/src/entries.tsx, examples/33_promise/waku.config.ts, examples/36_form/src/als.ts, examples/36_form/src/components/funcs.ts, examples/36_form/src/entries.tsx, examples/36_form/tsconfig.json, examples/36_form/waku.config.ts, examples/37_css/src/entries.tsx, examples/37_css/waku.config.ts, examples/41_path-alias/src/entries.tsx, examples/41_path-alias/waku.config.ts
=> chore(examples): migrate to new_defineEntries

examples/38_cookies/src/components/App.tsx
At some point, react throws an error with non serializable data. It seems that it's already fixed, so let's revert the example.
https://github.com/dai-shi/waku/pull/875/files#diff-741ff37ef190c7b4874d864c43f559ab1151ec213d97265317a83111bd6a33feR15-R16
=> chore(examples): server console.log

e2e/fixtures/rsc-basic/src/entries.tsx, e2e/fixtures/rsc-basic/waku.config.ts, e2e/fixtures/rsc-css-modules/src/entries.tsx, e2e/fixtures/rsc-css-modules/waku.config.ts, e2e/fixtures/ssr-basic/src/entries.tsx, e2e/fixtures/ssr-basic/tsconfig.json, e2e/fixtures/ssr-basic/waku.config.ts, e2e/fixtures/ssr-context-provider/src/components/context-consumer.tsx, e2e/fixtures/ssr-context-provider/src/entries.tsx, e2e/fixtures/ssr-context-provider/tsconfig.json, e2e/fixtures/ssr-context-provider/waku.config.ts, e2e/fixtures/ssr-swr/src/entries.tsx, e2e/fixtures/ssr-swr/tsconfig.json, e2e/fixtures/ssr-swr/waku.config.ts, e2e/fixtures/ssr-target-bundle/src/components/App.tsx, e2e/fixtures/ssr-target-bundle/src/entries.tsx, e2e/fixtures/ssr-target-bundle/tsconfig.json, e2e/fixtures/ssr-target-bundle/waku.config.ts
=> chore(e2e): migrate to new_defineEntries

packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts
follows `\0` technique described in https://vite.dev/guide/api-plugin#virtual-modules-convention
related: https://github.com/vitejs/vite/issues/18223
=> fix(plugins): fix rscManagedPlugin

packages/waku/.swcrc
Divived from https://github.com/dai-shi/waku/pull/1012, I will need this to set debugger in editor like vscode or webstorm
=> chore: emit source map for debugging

packages/waku/src/router/create-pages.ts, packages/waku/tests/create-pages.test.ts
This change marks the type of static layouts to not receive `path` as a prop. For layouts to receive `path` as a prop, currently this will need to be made dynamic.
this also includes a fix to new_createPages where we consider the pattern of the staticPaths with slug paths to be the same pattern across each use of a staticPath as it is return from `getPathConfig`
=> fix(new_createPages): path prop for dynamic layouts only and fix type

e2e/fixtures/rsc-router/src/entries.tsx, e2e/fixtures/rsc-router/src/main.tsx, e2e/fixtures/rsc-router/src/routes/layout.tsx
=> chore(e2e): migrate to new_defineRouter

packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts, packages/waku/src/router/create-pages-utils/inferred-path-types.ts
Simplified generated type output for waku website as example:
=> fix(typegen): abstract DO_NOT_USE_pages away from pages.gen.ts

packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
See #1053 - the generated `wrangler.toml` file does not match Waku's new Cloudflare Workers based deployment, and is invalid TOML.
I updated the plugin to generate the same file as in the example: https://github.com/dai-shi/waku/blob/main/examples/44_cloudflare/wrangler.toml
Fixes #1053
=> fix(cloudflare): update default generated wrangler.toml

e2e/fixtures/use-router/src/TestRouter.tsx, e2e/fixtures/use-router/src/components/my-button.tsx, e2e/fixtures/use-router/src/pages/dynamic.tsx, e2e/use-router.spec.ts, packages/waku/src/router/client.ts
=> fix(use-router): router.push bug

packages/waku/package.json, pnpm-lock.yaml
https://react.dev/reference/rsc/server-functions
> While Server Functions in React 19 are stable and will not break between major versions, the underlying APIs used to implement Server Functions in a React Server Components bundler or framework do not follow semver and may break between minors in React 19.x.
=> chore: react version range in peerDeps

packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts, packages/waku/src/minimal/client.ts, packages/waku/src/router/client.ts, packages/waku/src/router/common.ts, packages/waku/src/router/define-router.ts
Previously, we weren't able to pass `skip` to function invocation.
This moves `skip` from search params to http headers, and it's always available.
=> fix(router): improve function returning components with `skip`

packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
This will fix the missing styles with vite 6 for #1012
It works by running js from the browser to create the styles with CSR in dev. Before we were extracting the source for plain css and passing those from the dev server in a <style> tag, but since that breaks in vite 6, this is an easy solution that will handle styles more consistently and without errors.
=> fix(style-dev): style css for dev with vite js module

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/lib/renderers/html.ts, packages/waku/src/lib/renderers/rsc.ts, packages/waku/src/lib/types.ts, packages/waku/src/lib/utils/stream.ts
=> fix(handler): return promise of stream with allReady

packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts, packages/waku/src/lib/renderers/html.ts
Let React handle html headers instead of injecting them as strings
=> fix(html): overriding default head

e2e/examples-smoke.spec.ts, package.json, packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-rsdw.ts, packages/website/vite.config.ts
- smoke test website in e2e tests
- fix runtime error for dev server related to client edge from react-server-dom-webpack
the error:
```
TypeError: globalThis.__WAKU_CLIENT_CHUNK_LOAD__ is not a function
at Object.get (file:///~/gitspace/waku/packages/waku/dist/lib/renderers/html.js:162:36)
at resolveClientReference (/~/gitspace/waku/node_modules/.pnpm/react-server-dom-webpack@19.0.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_webpack@5.97.1/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:28:60)
at resolveModule (/~/gitspace/waku/node_modules/.pnpm/react-server-dom-webpack@19.0.0_react-dom@19.0.0_react@19.0.0__react@19.0.0_webpack@5.97.1/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js:1755:29)
at …
```
=> chore(e2e): add website to smoke tests & fix dev server error

e2e/fixtures/define-router/src/entries.tsx, e2e/fixtures/rsc-basic/src/entries.tsx, e2e/fixtures/rsc-css-modules/src/entries.tsx, e2e/fixtures/ssr-basic/src/entries.tsx, e2e/fixtures/ssr-context-provider/src/entries.tsx, e2e/fixtures/ssr-swr/src/entries.tsx, e2e/fixtures/ssr-target-bundle/src/entries.tsx, examples/12_nossr/src/entries.ts, examples/31_minimal/src/entries.tsx, examples/32_minimal_js/src/entries.jsx, examples/33_promise/src/entries.tsx, examples/34_functions/src/entries.tsx, examples/35_nesting/src/entries.tsx, examples/36_form/src/entries.tsx, examples/37_css/src/entries.tsx, examples/38_cookies/src/entries.tsx, examples/39_api/src/entries.tsx, examples/41_path-alias/src/entries.tsx, examples/44_cloudflare/src/entries.tsx, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/lib/types.ts, packages/waku/src/router/define-router.ts, packages/waku/src/server.ts
=> breaking(minimal): handleBuild API for build

e2e/fixtures/use-router/src/TestRouter.tsx, packages/waku/src/router/client.ts
fixes #791
- router.reload
- router.back
- `<Link to={foo} />`
- router.replace 
- router.push
=> feat(use-router): change default scroll restoration behavior

examples/37_css/package.json, examples/37_css/src/components/app.css, examples/37_css/src/components/layout.tsx, examples/37_css/waku.config.ts, pnpm-lock.yaml
for #1102
This reverts #1105 and reopens #750.
=> fix(stylex): revert to vite-plugin-stylex-dev for now

.github/workflows/e2e.yml, .github/workflows/test.yml
only run E2E test when necessary to reduce unused CI check and cost
=> ci: split e2e test to a single file

e2e/fixtures/ssr-basic/src/components/Counter.tsx, e2e/ssr-basic.spec.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts, packages/waku/src/lib/renderers/html.ts, packages/waku/src/minimal/client.ts
=> fix: hydration error with useId

.github/workflows/cd.yml, .github/workflows/e2e.yml, .github/workflows/test.yml
* In CI, `pnpm install` means `pnpm install --frozen-lockfile`
* Update `node-version` `18` to `20`
* We don't need to specify `cache-dependency-path` in `actions/setup-node`, monorepo only use `./pnpm-lock.yaml`, also we only use `./pnpm-lock.yaml`
=> chore(.github/workflows): update 'node-version' to 20, simplify 'pnpm install', 'actions/setup-node'

packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts, packages/waku/tests/create-pages.test.ts
This adds api route handling in createPages with tests
=> feat(create-pages): api handling

eslint.config.js, tsconfig.eslint.json
* remove comment about `.wrangler`
* Simplify the array inside `includes` in `tsconfig.eslint.json`.
=> chore(eslint): remove comment about '.wrangler', simplify the array inside 'includes' in 'tsconfig.eslint.json'

e2e/create-pages.spec.ts, e2e/fixtures/create-pages/package.json, e2e/fixtures/create-pages/src/components/ErrorBoundary.tsx, e2e/fixtures/create-pages/src/components/ErrorPage.tsx, e2e/fixtures/create-pages/src/components/ErrorRender.tsx, e2e/fixtures/create-pages/src/components/HomeLayout.tsx, e2e/fixtures/create-pages/src/components/ServerThrows/Counter.tsx, e2e/fixtures/create-pages/src/components/ServerThrows/index.tsx, e2e/fixtures/create-pages/src/components/funcs.ts, e2e/fixtures/create-pages/src/entries.tsx, e2e/fixtures/rsc-basic/src/components/App.tsx, e2e/fixtures/rsc-basic/src/components/ServerThrows/Counter.tsx, e2e/fixtures/rsc-basic/src/components/ServerThrows/actions.ts, e2e/fixtures/rsc-basic/src/components/ServerThrows/index.tsx, e2e/fixtures/ssr-catch-error/src/components/client-layout.tsx, e2e/fixtures/ssr-catch-error/src/components/server/throws.tsx, e2e/fixtures/ssr-catch-error/src/middleware/validator.ts, e2e/fixtures/ssr-catch-error/src/pages/_layout.tsx, e2e/fixtures/ssr-catch-error/src/pages/dynamic/_layout.tsx, e2e/fixtures/ssr-catch-error/src/pages/dynamic/index.tsx, e2e/rsc-basic.spec.ts, e2e/ssr-catch-error.spec.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/minimal/client.ts, pnpm-lock.yaml
The additional ErrorFallback and Suspense examples seem to work well.
The tests I added for using the browser back button and for throwing an exception from a server function are failing though.
ref: #967
=> chore: react-server (dynamic ssr and rsc) error handling e2e tests

e2e/create-pages.spec.ts, packages/waku/src/minimal/client.ts, packages/waku/src/router/client.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts
=> refactor: error handling

packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts
Changes the netlify functions output dir from netlify/functions to netlify-functions.
This is a breaking change for existing netlify projects using dynamic rendering. It requires updating the functions directory for existing projects from the default "netlify/functions" to "netlify-functions".
Edit the netlify.toml `[functions]` section and set
```
directory = "netlify-functions"
```
In a monorepo, the directory value needs to also include the base path from the root of the monorepo.
Fixes #909
=> fix: netlify relative fs path

packages/waku/src/lib/plugins/vite-plugin-dev-commonjs.ts
=> fix(dev): do not process mdx files in devCommonJsPlugin

e2e/fixtures/monorepo/pnpm-workspace.yaml
Sorry... I missed adding this file in #1079.
=> chore: e2e pnpm-workspace.yaml file

packages/waku/src/router/client.ts
fixes #1134
I'd like to have more robust testing for these path types but that seems lower priority to setup for now. Maybe a v1 alpha task?
=> fix(path-types): allow # and ? links for to prop

examples/21_create-pages/src/entries.tsx
example can respond with simple response object that can accept anything the normal `Response` object would handle
https://developer.mozilla.org/en-US/docs/Web/API/Response/Response
=> fix(create-pages-eg): show example with simple response

e2e/define-router.spec.ts, e2e/fixtures/define-router/private/hi.txt, e2e/fixtures/define-router/src/entries.tsx
add api handling support to define-router spec and test the result
=> test(define-router): handleApi and getApiConfig e2e tests

e2e/fixtures/create-pages/src/entries.tsx, examples/21_create-pages/src/entries.tsx, packages/waku/src/router/create-pages.ts, packages/waku/tests/create-pages.test.ts
refactor createApi to support multiple handlers on dynamic route with single createApi call
this also enforces with types static paths only have a single handler
=> refactor(create-pages): dynamic handlers and static handler

e2e/fixtures/rsc-basic/src/components/App.tsx, e2e/fixtures/ssr-basic/public/background.css, e2e/fixtures/ssr-basic/public/hello.js, e2e/fixtures/ssr-basic/src/components/App.tsx, packages/waku/src/lib/middleware/dev-server-impl.ts
=> fix: use case with preload

.github/workflows/test.yml
#1104 split e2e and test, but it also copies `concurrency`. This isn't necessary for Test, and it caused a problem: https://github.com/dai-shi/waku/actions/runs/12760172620/job/35565189012
=> chore: github workflow not to cancel for test

examples/05_compiler/package.json, pnpm-lock.yaml
While working on #1118, I noticed an e2e test fails with the latest canary. It seems to related with react-compiler.
=> fix: react-compiler with the latest canary

packages/website/package.json, packages/website/src/pages/api/rss.xml.ts
adds rss xml endpoint to the website.
should we add a button to link to the feed somewhere?
sample feed from time of PR:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<atom:link href="https://waku.gg/api/rss.xml" rel="self" type="application/rss+xml" />
<title>Waku</title>
<link>https://waku.gg</link>
<description>The minimal React framework</description>
<item>
<title>Introducing Waku</title>
<link>https://waku.gg/blog/introducing-waku</link>
<pubDate>Tue, 12 Dec 2023 00:00:00 GMT</pubDate>
<description>Learn about the minimal React framework and how it enables RSC features.</description>
<guid isPermaLink="true">https://waku.gg/blog/introducing-waku</guid>
</item>
<item>
<title>Introducing createPages</title> …
```
=> feat(website): add rss feed

e2e/fixtures/create-pages/src/entries.tsx, examples/21_create-pages/src/entries.tsx, packages/waku/src/router/create-pages.ts, packages/waku/src/router/fs-router.ts, packages/waku/tests/create-pages.test.ts
=> refactor(create-pages): mode changed to render for createApi

e2e/fixtures/monorepo/packages/context-library/package.json, e2e/fixtures/monorepo/packages/context-library/src/context-consumer.js, e2e/fixtures/monorepo/packages/context-library/src/context-provider.js, e2e/fixtures/monorepo/packages/context-library/src/index.d.ts, e2e/fixtures/monorepo/packages/context-library/src/index.js, e2e/fixtures/monorepo/packages/waku-project/package.json, e2e/fixtures/monorepo/packages/waku-project/src/pages/index.tsx, e2e/monorepo.spec.ts, packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-analyze.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
=> fix: React context loss in a monorepo setup

packages/waku/src/router/create-pages-utils/inferred-path-types.ts
this fix brings back the autocomplete for `PageProps`:
this was just missed in an earlier refactor of the types
=> fix(types): PageProps was missing type hints for paths

e2e/create-waku.spec.ts, packages/create-waku/src/index.ts
I'm not sure if some users rely on stdout/stderr difference, but if it's okay, it'd be okay.
=> fix(cli): no stderr log and refactor spec

e2e/examples-smoke.spec.ts
The error happens specific to 53_islands which keeps loading after the initial render. I'm not sure if there's a better way to fix this.
=> chore(e2e): ignore known errors

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/types.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/server.ts
Previously, it was a single JSON object. Separating it into multiple files theoretically enables lazy loading.
=> feat: separate build data into files

examples/36_form/src/components/Counter.tsx, examples/36_form/src/components/Form.tsx, examples/36_form/src/components/ServerForm.tsx
fixing the FIXME for the server form with a more robust form example
also removed the type references since they didn't seem to do anything
=> docs: Form example improvement and removed unused type references

packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts
I was skeptical about it. Actually, we tried kind of both in our iteration.
Having `skip` logic in defineRouter can't support actually skipping rendering component. So, this moves the logic and the responsibility from define-router to create-pages.
cc @tylersayshi
=> refactor: move skip logic from define-router to create-pages

packages/waku/src/router/define-router.ts
There was a bug that `skip` didn't work for rootElement and routeElement. This also does some refactors.
=> fix(router): static route handling

examples/12_nossr/waku.config.ts
otherwise, reloading `http://localhost:3000/about` becomes 404.
=> fix(examples): nossr with fallback middleware

e2e/fixtures/define-router/src/entries.tsx, examples/35_nesting/src/entries.tsx, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/lib/renderers/html.ts, packages/waku/src/lib/types.ts, packages/waku/src/minimal/client.ts, packages/waku/src/router/client.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts
elements are actually used beside react nodes. For now, we hack with an array. But, this should support it better, even though it loses some type checks.
=> feat(core): generalize elements

packages/waku/src/client.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/src/lib/utils/treeshake.ts, packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
This enables an experimental `allowServer`. I'm not sure if this is going to be finalized.
=> feat(core): new transform for client references

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/server.ts
- support both serializable and non-serializable platform data
- simplify buildOptions
It's a refactor, but it's also kind of a breaking change, if people depend on the unstable features.
=> refactor: prefer platformData over platformObject

examples/11_fs-router/src/entries.tsx, examples/12_nossr/src/entries.ts, packages/waku/src/client.ts, packages/waku/src/config.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/src/lib/renderers/html.ts, packages/waku/src/minimal/client.ts, packages/waku/src/router/client.ts, packages/waku/src/router/define-router.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/router/server.ts, packages/waku/src/server.ts, packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
To make it consistent:
- `unstable_` functions are subject to change
- `INTERNAL_` functions are not public API (and implies `unstable_`)
=> fix: prefix for exported functions

docs/minimal-api.mdx
#921 
`handleBuild` is very complicated.
=> docs: update minimal-api

e2e/create-pages.spec.ts, e2e/fixtures/create-pages/src/components/HomeLayout.tsx, e2e/fixtures/create-pages/src/entries.tsx, packages/waku/src/lib/utils/path.ts, packages/waku/src/router/create-pages.ts, packages/waku/src/router/define-router.ts, packages/waku/tests/create-pages.test.ts, packages/waku/tests/path.test.ts
escape hatch for allowing any routing conventions at all
=> feat(create-pages): support for exactPath

packages/create-waku/src/index.ts
Closes: #1228 
This change adds support for the `bun` package manager when running `create-waku`.
From some local testing, it seemed like bun didn't set the `process.env.npm_config_user_agent` variable correctly (it does so when running `bun repl` though...), so instead I opted to fallback to checking if the `Bun` global was defined, which seems to be present when running the package via `bun`.
I was also considering checking against `process.argv0` which I think would be `'bun'`, however I'm not 100% sure since I was running the cli manually via `bun ./path/to/cli.js` vs `bun create waku`.
=> feat(create-waku): Add support for bun package manager

packages/create-waku/package.json
It's been there since v0.10.2.
https://unpkg.com/browse/create-waku@0.10.2/template/01_template/tsconfig.tsbuildinfo
=> fix(create-waku): remove tsbuildinfo files from template

e2e/create-pages.spec.ts, e2e/fixtures/create-pages/src/components/DynamicLayout.tsx, e2e/fixtures/create-pages/src/entries.tsx, packages/waku/src/router/create-pages.ts
The logic seemed to be reversed when checking if the current layout segment is dynamic or static (see `!` in create-pages.ts), so the `path` prop was never provided.
Didn't run the E2E tests locally but verified by adding a temp test to `create-pages.test.ts` locally.
=> fix(create-pages): Ensure dynamic layouts receive path prop

e2e/fixtures/rsc-asset/package.json, e2e/fixtures/rsc-asset/src/components/App.tsx, e2e/fixtures/rsc-asset/src/components/test-client.txt, e2e/fixtures/rsc-asset/src/components/test-server.txt, e2e/fixtures/rsc-asset/src/entries.tsx, e2e/fixtures/rsc-asset/src/main.tsx, e2e/fixtures/rsc-asset/tsconfig.json, e2e/fixtures/rsc-asset/waku.config.ts, e2e/rsc-asset.spec.ts, packages/waku/src/lib/builder/build.ts, pnpm-lock.yaml, tsconfig.e2e.json
- Related https://github.com/dai-shi/waku/issues/1245
While trying to come up with a simpler example, I realized that server-only asset concept doesn't actually exist as a builtin Vite feature and this can be only achieved by using Rollup's `emitFile + import.meta.ROLLUP_FILE_URL_(id)` feature on Vite ssr build via custom plugin. So, I think cloudflare wasm import scenario I mentioned in the issue is fairly an edge case.
Nonetheless, there might be other vite/rollup plugins relying on `ROLLUP_FILE_URL` feature on server build, so simply replacing `rename` with `copyFile` to save this specific case might be still worth it.
=> fix: keep server assets on server build

packages/create-waku/src/index.ts
I noticed that running `bun create waku@latest` and `bunx create-waku@latest` didn't seem to detect `bun` as the package manager as expected based on my changes in #1229.
However - I was able to verify that both formats should work when I tested with a new dummy package: `create-debug-create`
```sh
bun create debug-create@latest
bunx create-debug-create@latest
```
will print some things to the console (e.g. `process.env`, `process`, etc).
Based on running both of those - it seems like the `npm_config_user_agent` env var _does_ get populated with `bun` as expected (not sure how I was testing before where it didn't work - maybe just with running the CLI directly via `bun ./cli.mjs`?)
=> fix(create-waku): Fix detection of bun using npm_config_user_agent env var

packages/waku/src/router/create-pages.ts
This change adds support for `createApi` handlers to handle both `HEAD` and `OPTIONS` request methods.
=> feat(create-pages): Support HEAD and OPTIONS api handlers

packages/waku/src/router/create-pages.ts
Follow up to #1269, allowing for support for all request methods to be handled by handlers within `createApi`
=> feat(create-pages): Allow for all request methods within createApi

packages/waku/src/cli.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/middleware/handler.ts, packages/waku/src/lib/middleware/types.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/lib/renderers/html.ts, packages/waku/src/lib/renderers/rsc.ts
(I'm still not sure how `onError` works. Isn't it documented?)
=> experimental: error callback for middleware

packages/waku/src/router/define-router.ts, packages/waku/tests/create-pages.test.ts
for #1296 (not the entire fix).
=> fix(define-router): pass through url for api

e2e/create-pages.spec.ts, packages/waku/src/router/client.ts, packages/waku/src/router/define-router.ts
Let me know if this approach is ok. The change makes it so that id's internally for routes are always decoded. This makes it so the prop is decoded when it is passed. It also fixes the runtime error. The runtime error happened when the id as being looked up in elements as decoded, but internally stored as encoded, so our invalid element id error was thrown.
fixes #1302
=> fix(router): decode path for storing elements and slug as prop

packages/waku/src/minimal/client.ts, packages/waku/src/router/client.ts
Continuing from https://github.com/dai-shi/waku/pull/1270#issuecomment-2688036257
=> refactor: 404 handling for static sites

docs/guides/aws-lambda.mdx, docs/guides/cloudflare.mdx, docs/guides/docker.mdx, docs/guides/getting-started.mdx, docs/guides/monorepo.mdx, docs/guides/react-compiler.mdx, docs/guides/router-fetch-strategy.mdx, docs/guides/stream-intercept.mdx, packages/website/private/contents/post-009.mdx, packages/website/src/components/icon.tsx, packages/website/src/components/navigation.tsx, packages/website/src/components/post-list.tsx, packages/website/src/components/post-page.tsx, packages/website/src/lib/get-file-name.ts, packages/website/src/pages/guides/[slug].tsx, packages/website/src/pages/guides/index.tsx
This is an idea for a router post. I am happy to reword, restructure or whatever.
It was helpful for me to organize my thoughts to look a bit closer at what is loaded when on each route, so I think a post to talk through some of this has some value.
Excited to hear what y'all think :)
=> docs: Waku router under the hood and add guides to website

packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/builder/constants.ts, packages/waku/src/lib/constants.ts, packages/waku/src/lib/middleware/dev-server-impl.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts, packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts, packages/waku/src/lib/plugins/vite-plugin-dev-commonjs.ts, packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts, packages/waku/src/lib/plugins/vite-plugin-nonjs-resolve.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-analyze.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-delegate.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts, packages/waku/src/lib/renderers/html.ts, packages/waku/src/router/fs-router.ts, packages/waku/src/server.ts
https://github.com/wakujs/waku/issues/1279#issuecomment-2740170122
=> expose unstable builder constants and functions

packages/waku/src/router/client.ts
https://github.com/dai-shi/waku/discussions/1037#discussioncomment-12481933
=> expose unstable enhancers from router

eslint.config.ts, package.json, pnpm-lock.yaml
I noticed not all the rules were running on all the files. I am still not sure this is 100% correct, but it runs the custom rules we had on all our files, before it wasn't.
=> chore(eslint): run rules on all files and add prefer-string-slice rule

e2e/fs-router.spec.ts, packages/waku/src/router/client.ts
=> feat: bypass Link click handler if alt click or defaultPrevented

README.md, packages/waku/package.json
Prior to this commit, when installing Waku from a git repository, the `dist` directory would not be built, and all `waku` CLI commands would throw an `ERR_MODULE_NOT_FOUND` error.
This commit adds a `prepare` command to `packages/waku/package.json`, which is just an alias for `pnpm run compile`.  pnpm will automatically run `prepare` when installing the package from a git repo, thus solving the problem.
Also, documentation about referencing a package inside a monorepo seems to be scarce and inaccurate (many sources specify incorrect syntax). Therefore, this commit adds instructions to the README on how to build an app that uses an experimental version of Waku.
=> Support installing Waku package from git repo

examples/07_cloudflare/.gitignore
I noticed we don't have a `.gitignore` in 07_cloudflare.
=> chore(create-waku): cloudflare .gitignore

e2e/fs-router.spec.ts
to fix the flakiness
from the docs it shows that macos is the one to use the meta key, which might help explain why the flakiness is only on mac
changing to alt should eliminate this as a possibility
=> test(fs-router): e2e test for alt click to use alt key

CONTRIBUTING.md, README.md
Follow-up to #1344.
This moves the instructions for trying experimental version of Waku from `README.md` to `CONTRIBUTING.md`.
This also adds a link to `CONTRIBUTING.md` in `README.md` in order to increase visibility.
---
Per https://github.com/wakujs/waku/pull/1344#discussion_r2027952490.
=> Move instructions for trying experimental version

packages/create-waku/src/index.ts, packages/create-waku/src/tests/cli-with-args.test.ts
We should keep the previous behavior.
=> fix(create-waku): do not ask package name by default

packages/waku/src/router/define-router.ts, packages/waku/src/router/server.ts
and make the internal parseRscParams function more robust. This feels a bit suboptimal though.
=> experimental(router): expose get rsc params

e2e/fixtures/rsc-basic/src/components/ClientCounter.tsx, e2e/rsc-basic.spec.ts, examples/08_jotai-demo/src/lib/waku-jotai/client.tsx, examples/35_nesting/src/components/Counter.tsx, examples/53_islands/src/main.tsx, examples/54_jotai/src/lib/waku-jotai/client.tsx, packages/waku/src/lib/renderers/html.ts, packages/waku/src/minimal/client.ts, packages/waku/src/router/client.ts
ref: https://github.com/wakujs/waku/pull/1391#discussion_r2069602375
This is a breaking change behavior-wise. We need to catch errors with try-catch and the error doesn't go to the error boundary by default.
=> feat: async refetch

e2e/fixtures/fs-router/src/pages/page-parts/_part-dynamic.tsx, e2e/fixtures/fs-router/src/pages/page-parts/_part-static.tsx, packages/waku/src/router/fs-router.ts
convention is: 
```ts
type PagePartFilename = `_part${string}.tsx`
// order must be defined in `getConfig`
```
=> refactor(router): use getConfig for order instead of filename

packages/create-waku/src/tests/cli-with-args.test.ts
This will make the test less flakey. Example failure: https://github.com/wakujs/waku/actions/runs/14988122768/job/42105823351
=> test(cli): extend example install test timeout

e2e/fixtures/rsc-basic/src/components/ServerPing/Counter.tsx, e2e/fixtures/rsc-basic/src/components/ServerPing/actions.tsx, e2e/rsc-basic.spec.ts, packages/waku/src/minimal/client.ts
fix #1420 
To be honest, I'm not sure if server action should trigger suspense or not. It was the intention in #1396 to make `callServerRsc` and `refetch` somewhat consistent. We should learn the expected behavior more in the future.
=> fix: Cannot update a component ("Root") while rendering a different component warning

packages/waku/src/router/client.ts
These functions can be async. The current `() => void` type shows an error if we pass an async function to `unstable_startTransition`.
=> chore: use React.TransitionFunction type for unstable_startTransition def

e2e/create-pages.spec.ts, e2e/fixtures/create-pages/src/components/LongSuspenseLayout.tsx, e2e/fixtures/create-pages/src/entries.tsx, packages/waku/src/router/client.ts
Part of the fix for #1437.
It turns out that #1437 is reporting multiple issues:
1. Showing preview element content instead of a transition when navigating to a previously visited page. That issue is replicated with the e2e tests in this PR and fixed.
2. Updating the url before changing the route. I'm expecting the url to not update until the new page has loaded. I opened #1459.
3. The changeRoute function completes before the page component has streamed any data.
The third issue is hard to test without using unstable_events.
=> fix: continue transition with waku/router Link

packages/waku/src/lib/middleware/dev-server-impl.ts
Fixes: #1464 
This is maybe a bit of a naive fix - but it uses the underlying OS (or an implementation of Node.js / the JS runtime in use while running Waku) to select an available port and then we specify that within the Vite `server.hmr` options for the main vite server.
I tested applying a similar change to the two other places ([here](https://github.com/wakujs/waku/blob/0f5d360550a6c1deb9b34080a264b07f95467834/packages/waku/src/lib/utils/vite-loader.ts#L11-L19), and [here](https://github.com/wakujs/waku/blob/0f5d360550a6c1deb9b34080a264b07f95467834/packages/waku/src/lib/middleware/dev-server-impl.ts#L270-L325)) where we call `createServer` from `vite` - but it seems like those had no impact and making only this change seemed to fix the issue for me.
I tested this a bit manually, …
=> fix: automatically pick available hmr port

e2e/fixtures/rsc-basic/src/components/App.tsx, e2e/fixtures/rsc-basic/src/components/ClientCounter.tsx, e2e/rsc-basic.spec.ts
This adds a basic e2e test for `unstable_allowServer` capability.
=> test: add a spec for unstable_allowServer

e2e/fixtures/fs-router/src/functions/say-hello.tsx, e2e/fixtures/rsc-basic/modules/ai/src/server.js
I extracted a change from https://github.com/wakujs/waku/pull/1493. I found these two since my plugin rejects non async function with "use server".
=> test: ensure server function is async

e2e/broken-links.spec.ts
Extracted from https://github.com/wakujs/waku/pull/1493. This for-loop seems redundant since DEV / PROD runs are already split  as playwright projects.
=> test: remove redundant tests

docs/guides/cloudflare.mdx
The Cloudflare example [uses](https://github.com/wakujs/waku/blob/main/examples/07_cloudflare/package.json#L18) `v4.x` of `wrangler` which by default sets the `--include-runtime` flag.
Also, the example [uses](https://github.com/wakujs/waku/blob/main/examples/07_cloudflare/package.json#L7) a script called `cf-typegen`, not `build-cf-types`.
---
💖
=> fix(docs): drop experimental flag and update script name

packages/create-waku/src/tests/cli-with-args.test.ts
It looks like this one is frequently failing (including Vite ecosystem ci sometimes https://github.com/vitejs/vite-ecosystem-ci/actions/runs/16108041683/job/45446816642).
```
packages/create-waku test: ⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯
packages/create-waku test:  FAIL  src/tests/cli-with-args.test.ts > create-waku CLI with args > accepts example option from command line
packages/create-waku test: AssertionError: expected '' to contain 'Setting up project...'
packages/create-waku test: - Expected
packages/create-waku test: + Received
packages/create-waku test: - Setting up project...
packages/create-waku test:  ❯ src/tests/cli-with-args.test.ts:122:20
packages/create-waku test:     120|       { cwd: import.meta.dirname, timeout: 30000, reject: false },
packages/create-waku test:     121| …
```
=> test: add debug logs for flaky create-vite test failure

packages/waku/src/router/client.ts
Extracted from https://github.com/wakujs/waku/pull/1493
I noticed that there are duplicate RSC fetching on server-side redirection of http://localhost:3000/async when running `pnpm -C e2e/fixtures/ssr-redirect dev`. This is because `StrictMode` triggering `useEffect` twice inside `Redirect` error boundary. I added `WeakMap` of `Error` instance to avoid triggering `changeRoute` twice. This just counters against `StrictMode`, so it's not a fundamental solution though.
It looks like this was causing flakiness on Vite RSC PR https://github.com/wakujs/waku/pull/1493, so I moved a fix separately here since this affects only router implementation.
<details><summary>Network devtools before/after</summary>
See `destination.txt` request at the end:
</details>
=> fix: fix double fetch on client after server redirection

e2e/fixtures/monorepo/pnpm-workspace.yaml, e2e/multi-platform.spec.ts, e2e/partial-build.spec.ts, e2e/render-type.spec.ts, e2e/utils.ts, packages/waku/src/lib/builder/build.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-resolve-rsdw.ts
Problem: monorepo spec doesn't pass locally. It looks like, when it seems to work, it reuses `standaloneDir` wrongly.
=> fix monorepo with pnpm and yarn

.github/workflows/e2e.yml, e2e/examples-smoke.spec.ts, examples/37_css-stylex/src/pages/index.tsx, examples/37_css-vanilla-extract/src/pages/index.tsx, playwright.config.ts
smoke tests has been ignored since #1463.
I'm not sure if it's a leftover or an intentional change by @himself65 , but this reverts it.
=> e2e: recover smoke tests

e2e/utils.ts
I found that monorepo yarn case is using the package just downloaded from npm and not the one build locally. This PR changes `prepareStandaloneSetup` to rely on `overrides/resolutions` instead of `add xxx.tar.gz` command to enforce locally built package.
=> test: fix monorepo yarn to use local build

e2e/utils.ts
`pnpm` is faster and I think we should use this by default since the purpose is the isolation.
=> test: use pnpm by default for `prepareStandaloneSetup`

packages/waku/src/lib/renderers/html.ts, packages/waku/src/minimal/client.ts
- Closes https://github.com/wakujs/waku/issues/1496
To understand better the nature of the React SSR bug https://github.com/facebook/react/issues/33937, this is an alternative approach of https://github.com/wakujs/waku/pull/1542.
See here https://github.com/facebook/react/issues/33937#issuecomment-3091349011 for how two approach differs.
I might like this approach better than adding DIY `use` since this way React SSR bug condition is better manifested by using only React API.
=> fix: workaround `React.use` SSR bug by wrapping extra component

e2e/fixtures/monorepo/package.json, pnpm-lock.yaml
npm peer dep resolution is a bit silly and it's installing react 19.1.1 and react-dom 19.1.0, which breaks the test. 
https://github.com/wakujs/waku/actions/runs/16591870176
```
[Child Process Error: e2e/utils.ts#L0](https://github.com/wakujs/waku/pull/1564/files#annotation_37188527137)
stderr: Error: Incompatible React versions: The "react" and "react-dom" packages must have the exact same version. Instead got:
- react:      19.1.1
- react-dom:  19.1.0
Learn more: https://react.dev/warnings/version-mismatch
```
I don't think React version resolution is the point of this test case, but it's for monorepo client component package compatibility, so ensuring React version here seems fine to reduce the noise on new React release.
=> test: enforce react version for npm monorepo

packages/waku/src/lib/renderers/html.ts
There's a FOUC regression. It's caused by my change in #1514.
This feels like an ad-hoc fix. I wonder if #1493 fixes completely.
=> fix: fouc in website

e2e/wildcard-api-routes.spec.ts, packages/waku/src/lib/utils/path.ts, packages/waku/tests/create-pages.test.ts, packages/waku/tests/path.test.ts
Fixes: https://github.com/wakujs/waku/issues/1518
=> feat: support catch all on router api

e2e/ssr-redirect.spec.ts
This is flaky and I can reproduce it locally either via `pnpm e2e-dev e2e/ssr-redirect.spec.ts -g 'access async page directly'` or just manually `pnpm -C e2e/fixtures/ssr-redirect dev` and accessing http://localhost:3000/async. It's likely due to after `@vitejs/plugin-rsc` migration, initial js waterfall makes hydration slower on dev. This PR fixes flakiness by retrying only this assertion though eventually we should figure out the actual cause.
=> test: retry dev async redirection test

e2e/fixtures/ssr-basic/private/config.ts, e2e/fixtures/ssr-basic/src/components/App.tsx, e2e/ssr-basic.spec.ts, packages/waku/src/lib/plugins/vite-plugin-rsc-private.ts, packages/waku/src/vite-rsc/plugin.ts
Fixes: https://github.com/wakujs/waku/issues/1569
=> feat: allow read private folder during rsc

packages/waku/tests/allow-server.test.ts
Extracted from https://github.com/wakujs/waku/pull/1597
Similar test already exists in `packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts`, but I copied it to target `allowServerPlugin` instead of `rscTransformPlugin`.
=> test: unit test `allowServerPlugin`

e2e/fixtures/fs-router/src/pages/_layout.tsx, e2e/fixtures/fs-router/src/pages/css-split/_layout.tsx, e2e/fixtures/fs-router/src/pages/css-split/index.tsx, e2e/fixtures/fs-router/src/pages/css-split/page1/_layout.tsx, e2e/fixtures/fs-router/src/pages/css-split/page1/index.tsx, e2e/fixtures/fs-router/src/pages/css-split/page1/nested/index.tsx, e2e/fixtures/fs-router/src/pages/css-split/page1/styles.css, e2e/fixtures/fs-router/src/pages/css-split/page2/_layout.tsx, e2e/fixtures/fs-router/src/pages/css-split/page2/index.tsx, e2e/fixtures/fs-router/src/pages/css-split/page2/nested/index.tsx, e2e/fixtures/fs-router/src/pages/css-split/page2/styles.css, e2e/fs-router.spec.ts
- Closes https://github.com/wakujs/waku/issues/752
This adds a test case for css code splitting in fs-router. The test verifies css is separately loaded initially depending on page structure, but as per React's "special rendering behavior", once loaded styles cannot be removed later on after route change. https://react.dev/reference/react-dom/components/style
> React may leave the style in the DOM even after the component that rendered it has been unmounted.
https://github.com/user-attachments/assets/8b48ddd7-cd7c-4b4d-bd0a-c9dba0b1015b
=> test: test css code split

.github/workflows/e2e.yml
This may or may not related to the canary failure https://github.com/wakujs/waku/pull/1611, but I noticed pkg.pr.new is returning stale package when installing `@524` (it's possible that this is because of pnpm bug of local cache, so it might not happen on fresh CI). I updated ci job to specify by the latest commit to ensure latest build.
=> ci: ensure latest rsc plugin canary/experimental package

packages/waku/src/lib/vite-rsc/cli.ts, packages/waku/src/lib/vite-rsc/deploy/aws-lambda/plugin.ts, packages/waku/src/lib/vite-rsc/deploy/cloudflare/plugin.ts, packages/waku/src/lib/vite-rsc/deploy/deno/plugin.ts, packages/waku/src/lib/vite-rsc/deploy/netlify/plugin.ts, packages/waku/src/lib/vite-rsc/deploy/partykit/plugin.ts, packages/waku/src/lib/vite-rsc/deploy/vercel/plugin.ts, packages/waku/src/lib/vite-rsc/plugin.ts
Rsc plugin by default creates flat `dist/{name}`, but for normal use case, it looks cleaner to have only two directories for server and client. This is also a minor requirement for `@cloudflare/vite-plugin` https://github.com/wakujs/waku/pull/1655, so moving this change to here first.
=> refactor: rename server build output to `dist/server` and `dist/server/ssr`

packages/waku/src/lib/vite-rsc/plugin.ts
This should've been removed together during https://github.com/wakujs/waku/pull/1645.
=> refactor: remove unused `configurePreviewServer`

.github/workflows/e2e.yml
=> chore(ci): downgrade windows 2022 for e2e (temporary)
