- src/middleware/rscDev.ts
Both `rsc` and `Counter.tsx` fetching start immediately.
> fix: send client bundle in the initial response

- examples/01_counter/src/index.tsx
- examples/02_async/src/index.tsx
- examples/03_promise/src/index.tsx
- examples/04_callserver/src/Counter.tsx
- examples/04_callserver/src/funcs.ts
- examples/04_callserver/src/index.tsx
- examples/05_mutation/src/Counter.tsx
- examples/05_mutation/src/index.tsx
- examples/06_nesting/src/Counter.tsx
- examples/06_nesting/src/index.tsx
- src/client.ts
It's a breaking change in wakuwork/client API.
Also, some examples are updated.
> new `serve` func

- examples/05_mutation/src/Counter.tsx
- src/client.ts
https://twitter.com/dai_shi/status/1639937951596703745
> alternative API for mutate

- src/client.ts
- src/middleware/rewriteRsc.ts
- src/router/client.ts
https://twitter.com/dai_shi/status/1640151270806913024
> new RSC request protocol

- examples/05_mutation/src/funcs.ts
- examples/07_router/routes/index.tsx
- examples/07_router/routes/nested.tsx
- examples/07_router/routes/nested/qux.tsx
- examples/07_router/src/Counter.tsx
- src/client.ts
- src/middleware/rewriteRsc.ts
- src/router/client.ts
- src/router/common.ts
- src/router/server.ts
- refactor wakuwork/client
- refactor wakuwork/router
- add transition for Link
- experimental prefetch on hover
- reuse intermediate route with router
> Various improvements

- src/middleware/rscDev.ts
- src/middleware/rscPrd.ts
...because @gaearon suggested so in @bholmesdev 's stream https://www.twitch.tv/videos/1779925131.
> Prefer using createElement before passing to renderToPipeableStream

- examples/01_counter/index.html
- examples/02_async/index.html
- examples/03_promise/index.html
- examples/04_callserver/index.html
- examples/05_mutation/index.html
- examples/06_nesting/index.html
- examples/07_router/index.html
Just to mitigate UX by showing a little spinner when we don't have SSR (which is default.)
https://user-images.githubusercontent.com/490574/231416726-929a3212-2b74-47dc-949a-ce0649288732.mov
> Loading spinner

- README.md
- cli-dev.js
- cli-dev.ts
- cli.js
- examples/01_counter/package.json
- examples/02_async/package.json
- examples/03_promise/package.json
- examples/04_callserver/package.json
- examples/05_mutation/package.json
- examples/06_nesting/package.json
- examples/07_router/package.json
- package.json
- pnpm-lock.yaml
- postcss.config.js
- src/router/client.ts
- src/router/common.ts
- src/router/server.ts
- tailwind.config.js
- website/entries.ts
- website/index.html
- website/package.json
- website/routes/index.tsx
- website/routes/install.tsx
- website/routes/introduction.tsx
- website/routes/practices.tsx
- website/routes/practices/minimal.tsx
- website/routes/practices/router.tsx
- website/src/Code.tsx
- website/src/index.css
- website/src/index.tsx
- add website
- update wakuwork/router
- use worker (instead of node options)
> feat: add website

- src/middleware/rscDev.ts
- src/middleware/rscPrd.ts
> fix: add `file://` to `entriesFile` in Windows

- .github/workflows/ci.yml
- e2e/01_counter.spec.ts
- package.json
- playwright.config.ts
- pnpm-lock.yaml
Wakuwork is a nice project, but the one concern is the lack of test cases. I tried to add vitest support, but since this is more like a server cli, I think `playwright` is more suitable for this repo
> feat: support e2e test using playwright

- .github/workflows/cd.yml
- .github/workflows/ci.yml
While I'm still looking for a simpler alternative, this is something I use lately.
> chore: github workflows

- cli.js
- src/builder.ts
- src/cli-build.ts
- src/devServer.ts
- src/middleware/indexFallback.ts
- src/middleware/lib/common.ts
- src/middleware/lib/rsc-renderer-worker.ts
- src/middleware/lib/rsc-renderer.ts
- src/middleware/lib/rsc-utils.ts
- src/middleware/notFound.ts
- src/middleware/rewriteRsc.ts
- src/middleware/rscDev.ts
- src/middleware/rscPrd.ts
- src/middleware/staticFile.ts
- src/middleware/viteServer.ts
- src/prdServer.ts
- src/types.d.ts
Before #21, I need to refactor code. This is the first one. The second one may or may not come.
> refactor: rsc-renderer-worker

- examples/01_counter/entries.ts
- examples/02_async/entries.ts
- examples/03_promise/entries.ts
- examples/04_callserver/entries.ts
- examples/05_mutation/entries.ts
- examples/06_nesting/entries.ts
- examples/07_router/entries.ts
- src/middleware/lib/rsc-handler-worker.ts
- src/router/server.ts
- src/server.ts
- website/entries.ts
- website/routes/index.tsx
- website/routes/install.tsx
- website/routes/practices/minimal.tsx
- website/routes/practices/router.tsx
I didn't prefer the default export, but it can't be helped to abstract it better.
We would revisit this api once again before finalizing it.
> defineEntries API

- CHANGELOG.md
- src/server.ts
> fix: make getBuilder optional

- CHANGELOG.md
- examples/01_counter/package.json
- examples/02_async/package.json
- examples/03_promise/package.json
- examples/04_callserver/package.json
- examples/05_mutation/package.json
- examples/06_nesting/package.json
- examples/07_router/package.json
What a silly typo.
Reported by JLarky: https://twitter.com/JLarky/status/1664456542882791424
> fix(examples): config extension in script

- package.json
- src/lib/builder.ts
- src/lib/rsc-handler-worker.ts
- src/lib/rsc-handler.ts
there's an issue with the website: https://twitter.com/dai_shi/status/1661858992375894017
this should fix it.
> vercel build output api

- package.json
- pnpm-lock.yaml
- src/lib/builder.ts
Fixes: https://github.com/dai-shi/waku/issues/49
> fix: 'use client' warning

- src/cli.ts
``` shell
> waku --version  
0.11.1
```
> feat: enhance waku cli

- CHANGELOG.md
- src/lib/rsc-handler-worker.ts
It was a regression since #53.
> fix: collecting client modules

- package.json
- pnpm-lock.yaml
- src/cli.ts
- src/lib/builder.ts
- src/lib/middleware.ts
- src/lib/rsc-handler-worker.ts
- src/lib/rsc-handler.ts
- src/router/server.ts
- src/server.ts
This is a refactor to prefer for #66.
> refactor: split builder

- examples/01_counter/package.json
- examples/02_async/package.json
- examples/03_promise/package.json
- examples/04_callserver/package.json
- examples/05_mutation/package.json
- examples/06_nesting/package.json
- examples/07_router/package.json
- package.json
- pnpm-lock.yaml
- src/lib/builder.ts
and a small fix to follow up #63.
> chore: update dependencies

- src/lib/builder.ts
- src/lib/middleware/devServer.ts
- src/lib/middleware/rsc.ts
- src/lib/middleware/rsc/worker-api.ts
- src/lib/middleware/rsc/worker-impl.ts
I think it was a neat idea, but it's too complicated. This one simply relies on some conventions.
> refactor: eliminate client entries

- examples/01_counter/src/index.html
- examples/02_async/src/index.html
- examples/03_promise/src/index.html
- examples/04_callserver/src/index.html
- examples/05_mutation/src/index.html
- examples/06_nesting/src/index.html
- examples/07_router/src/index.html
- website/src/index.html
- run `pnpm examples:dev:07_router`
- navigate to `http://localhost:3000/nested/baz`
- refresh the page
- open the network tab in the browser's dev tools
- observe that the request URL for `main.tsx` is displayed as `http://localhost:3000/nested/main.tsx`
> fix: Resolve main.tsx URL on nested route refresh

- CHANGELOG.md
- src/lib/builder.ts
- src/lib/middleware/rsc/worker-impl.ts
close #107 
Unfortunately, there's no ultimate solution. For now, let's work it around.
That said, any ideas are appreciated to make it better.
> fix: hacks for windows filesystem

- CHANGELOG.md
- examples/09_cssmodules/src/index.html
- src/lib/builder.ts
- src/lib/config.ts
- src/lib/middleware/devServer.ts
- src/lib/middleware/rsc/worker-api.ts
- src/lib/middleware/rsc/worker-impl.ts
- src/lib/middleware/ssr.ts
- src/lib/vite-plugin/rsc-delegate-plugin.ts
- src/lib/vite-plugin/rsc-hmr-plugin.ts
- src/lib/vite-plugin/rsc-index-plugin.ts
> feat: css modules

- packages/waku/src/client.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/middleware/devServer.ts
- packages/waku/src/lib/middleware/rsc/worker-impl.ts
> fix(waku/client): CJS import hack

- packages/waku/src/client.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/middleware/rsc/utils.ts
Just noticed a bug. I think there should be a better way to avoid human coding errors.
> fix: prefetch default hack

- README.md
_serioursly_ → _seriously_
__PS__: This looks like an interesting project. Thanks for working on it. Excited to see how it progresses!
💖
> Fix minor typo in `readme.md`

- packages/waku/src/cli.ts
- packages/waku/src/config.ts
Corrected some spelling mistakes in words 🍭
> fix: minor typo

- packages/waku/src/node-loader.ts
Upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65490
> fix: type on load hook

- README.md
- packages/waku/package.json
- packages/website/src/routes/page.tsx
> fix(readme): reframe the tagline with emoji

- .gitignore
- examples/01_counter/tsconfig.json
- examples/02_async/tsconfig.json
- examples/02_async/tsconfig.node.json
- examples/03_promise/tsconfig.json
- examples/04_callserver/tsconfig.json
- examples/05_mutation/tsconfig.json
- examples/06_nesting/tsconfig.json
- examples/07_router/tsconfig.json
- examples/07_router/tsconfig.node.json
- examples/08_cookies/tsconfig.json
- examples/09_cssmodules/tsconfig.json
- examples/10_dynamicroute/tsconfig.json
- examples/10_dynamicroute/tsconfig.node.json
- examples/11_form/tsconfig.json
- package.json
- packages/create-waku/tsconfig.json
- packages/waku/tsconfig.json
- packages/website/tsconfig.json
just to make them a little more consistent.
> refactor: tidy up tsconfig files

- packages/website/package.json
- packages/website/src/components/app.tsx
- packages/website/src/components/code.tsx
- packages/website/src/components/showhide.tsx
- pnpm-lock.yaml
Having bright is a good test because it has `server-only` internally.
This could be a new example, but we would be having it eventually.
> website: add bright back

- .github/workflows/ci.yml
- package.json
- scripts/postinstall.js
Only fixes: https://github.com/dai-shi/waku/issues/175
There are too many compatibility issues on Windows. I want to make it step by step.
First is to fix install pnpm
> build: fix postinstall error on windows

- CHANGELOG.md
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/vite-plugin/rsc-analyze-plugin.ts
- packages/website/src/components/button.tsx
There was a limitation revealed by https://github.com/dai-shi/waku/pull/166#discussion_r1401463376.
> fix: support common component that can be used both in RSC and RCC

- examples/08_cookies/db/items.json
- examples/08_cookies/src/components/App.tsx
- examples/08_cookies/src/entries.tsx
We had this use case in mind but haven't actually tried.
> add fs access example

- package.json
- packages/waku/src/lib/middleware/rsc/ssr.ts
- pnpm-lock.yaml
Now, we have more control with the webpack hack.
> refactor: ssr for dev

- examples/08_cookies/dev.js
- examples/08_cookies/start.js
- packages/waku/src/cli.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/middleware/connectWrapper.ts
- packages/waku/src/lib/middleware/honoWrapper.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/middleware/rsc/ssr.ts
- packages/waku/src/lib/middleware/rsc/worker-api.ts
- packages/waku/src/lib/middleware/rsc/worker-impl.ts
- packages/waku/src/lib/middleware/types.ts
- packages/waku/src/main.ts
- packages/waku/src/server.ts
> refactor: remove some node dependency

- e2e/fixtures/rsc-basic/package.json
- e2e/fixtures/ssr-basic/package.json
- examples/01_counter/package.json
- examples/02_async/package.json
- examples/03_promise/package.json
- examples/04_callserver/package.json
- examples/05_mutation/package.json
- examples/06_nesting/package.json
- examples/07_router/package.json
- examples/08_cookies/package.json
- examples/09_cssmodules/package.json
- examples/10_dynamicroute/package.json
- examples/11_form/package.json
- packages/waku/package.json
- packages/website/package.json
- pnpm-lock.yaml
> feat: use vite5

- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/middleware/rsc/ssr.ts
- packages/waku/src/lib/middleware/rsc/utils.ts
- packages/waku/src/lib/middleware/rsc/worker-impl.ts
I made some mistakes in my previous PRs, and noticed it while reviewing #181.
> fix: some code

- examples/08_cookies/dev.js
- examples/08_cookies/start.js
- package.json
- packages/waku/src/cli.ts
- packages/waku/src/config.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/middleware/rsc/ssr.ts
- packages/waku/src/lib/middleware/rsc/utils.ts
- packages/waku/src/lib/middleware/rsc/worker-api.ts
- packages/waku/src/lib/middleware/rsc/worker-impl.ts
- packages/waku/src/lib/utils/path.ts
- packages/waku/src/lib/utils/stream.ts
> refactor: pass config instead of cwd

- e2e/examples-smoke.spec.ts
Maybe fixed by https://github.com/dai-shi/waku/pull/210
Fixes: https://github.com/dai-shi/waku/issues/206
> test: enable all windows tests

- packages/waku/src/config.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/middleware/rsc/ssr.ts
- packages/waku/src/lib/middleware/rsc/worker-impl.ts
- packages/waku/src/lib/rsc/renderer.ts
- packages/waku/src/lib/utils/node-fs.ts
- packages/waku/src/lib/utils/path.ts
- packages/waku/src/lib/vite-plugin/rsc-delegate-plugin.ts
> Refactor: custom path utils

- packages/waku/src/config.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/rsc/renderer.ts
- packages/waku/src/lib/utils/stream.ts
> load index.html content from js file

- e2e/fixtures/rsc-router/README.md
- e2e/fixtures/rsc-router/package.json
- e2e/fixtures/rsc-router/src/entries.tsx
- e2e/fixtures/rsc-router/src/index.html
- e2e/fixtures/rsc-router/src/main.tsx
- e2e/fixtures/rsc-router/src/routes/foo/page.tsx
- e2e/fixtures/rsc-router/src/routes/layout.tsx
- e2e/fixtures/rsc-router/src/routes/page.tsx
- e2e/fixtures/rsc-router/tsconfig.json
- e2e/rsc-router.spec.ts
- packages/waku/src/config.ts
- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/router/server.ts
- pnpm-lock.yaml
- tsconfig.e2e.json
There was a regression in #165. static server doesn't work without file extensions.
> fix: static file with ext

- package.json
- packages/waku/src/lib/builder.ts
> fix: node env for build

- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/middleware/hono-prd.ts
- packages/waku/src/lib/plugins/vite-plugin-nonjs-resolve.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/src/lib/rsc/handler-prd.ts
- packages/waku/src/lib/rsc/html-renderer.ts
- packages/waku/src/lib/rsc/rsc-renderer.ts
- packages/waku/src/lib/rsc/worker-impl.ts
- packages/waku/src/lib/utils/node-fs.ts
- packages/waku/src/lib/utils/path.ts
- packages/waku/src/server.ts
well, it's still dynamic import, but it should be statically analyzable.
> refactor: avoid dynamic import

- packages/waku/src/lib/middleware/connect-utils.ts
- packages/waku/src/lib/plugins/vite-plugin-nonjs-resolve.ts
- packages/waku/src/lib/rsc/handler-prd.ts
- packages/waku/src/lib/rsc/html-renderer.ts
- packages/waku/src/lib/rsc/worker-api.ts
explicit catch to avoid build-time error.
> fix: avoid error with esbuild

- packages/website/src/components/code.tsx
- packages/website/src/entries.tsx
- packages/website/src/main.tsx
- packages/website/src/routes/blog/introducing-waku/page.tsx
- packages/website/src/routes/page.tsx
There's a limitation in waku/router, so it adds a workaround for now.
> website: use waku/router

- packages/waku/src/lib/builder.ts
- packages/website/vite.config.ts
> fix(vercel): no symlink for entire node_modules

- packages/waku/src/lib/rsc/handler-dev.ts
> fix: publicDir in DEV

- packages/waku/src/lib/builder.ts
- packages/waku/src/lib/rsc/html-renderer.ts
- packages/website/src/main.tsx
> fix: website issue with safari

- packages/waku/src/lib/rsc/html-renderer.ts
There was a regression in #252.
> fix: extra rsc

- packages/waku/src/lib/utils/merge-vite-config.ts
Resolves #266 
Just set the options to null when there's nothing there.
> fix: suppress terserOptions warning

- README.md
- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/output-deno.ts
> feat: output deno

- packages/waku/src/lib/rsc/html-renderer.ts
- packages/waku/src/lib/rsc/utils.ts
I noticed prefetching works unexpectedly with extra search params with SSR.
This changes the replacement more in a simple manner.
We might need tol refactor this code in the future anyway.
> fix(website): handle with extra search params

- README.md
- packages/waku/package.json
- packages/waku/src/cli.ts
- Update node engine spec
- Add error.message on startServer error
- refactor some code on cli.ts - applied DRY principle
> fix: Update engine spec and some refactoring on cli.ts

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/handlers/dev-worker-api.ts
- packages/waku/src/lib/handlers/dev-worker-impl.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/lib/renderers/html-renderer.ts
html renderer shouldn't import worker stuff.
> refactor: html-renderer

- README.md
- e2e/fixtures/rsc-router/src/entries.tsx
- examples/07_router/src/entries.tsx
- examples/10_dynamicroute/src/entries.tsx
- examples/10_dynamicroute/src/routes/layout.tsx
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/router/server.ts
- packages/website/src/components/code.tsx
- packages/website/src/entries.tsx
and some refactors. file-based router is very tricky. consider as an experiment for now.
> breaking(router): new api with getRoutePaths

- .github/workflows/ci.yml
- e2e/examples-smoke.spec.ts
- e2e/rsc-basic.spec.ts
- e2e/rsc-router.spec.ts
- e2e/ssr-basic.spec.ts
Fixes: https://github.com/dai-shi/waku/issues/283
Upstream: https://github.com/vitejs/vite/discussions/8146
> fix: flaky test

- .pnpmfile.cjs
- pnpm-lock.yaml
Refs: https://github.com/pnpm/pnpm/issues/2713#issuecomment-1141000426
> fix: dual version packages

- examples/11_form/tsconfig.json
- examples/11_form/tsconfig.node.json
- examples/11_form/vite.config.ts
- packages/waku/src/lib/handlers/handler-dev.ts
force vite to pre-bundle such packages to avoid dual instances in frontend
https://vitejs.dev/guide/dep-pre-bundling.html
> fix: vite include optmize

- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
https://vercel.com/docs/projects/environment-variables/system-environment-variables#system-environment-variables
> refactor(build, cli): generate vercel bundle automatically

- e2e/fixtures/rsc-router/src/entries.tsx
- examples/07_router/src/entries.tsx
- examples/10_dynamicroute/src/entries.tsx
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/common.ts
- packages/waku/src/router/server.ts
- packages/waku/src/server.ts
- packages/website/src/entries.tsx
I made some mistakes in #280.
Also, I had some misunderstanding with SSG.
This should fix and simplifies it.
> fix: url search handling

- packages/waku/src/client.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/server.ts
> fix(router): do not send Default on wire

- CHANGELOG.md
- package.json
- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/output-vercel.ts
- `--with-vercel-static` 👉 SSG
- Without it 👉 serverless function
> fix(vercel): option for static build

- packages/waku/src/lib/renderers/html-renderer.ts
Continuing from #311.
Vercel preview works but if we deploy to production, it fails. 🤷
> fix(website): possibly reduce hydration mismatch (2nd trial)

- packages/waku/src/lib/renderers/html-renderer.ts
> fix: ensure sending scripts after html chunks

- package.json
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/router/server.ts
- packages/website/vite.config.ts
> fix: various fixes for website and html renderer

- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
Continuing from #316.
I finally understand how to reproduce the issue locally.
It was really an edge case, but finally fixed. (and found a bug.)
> fix: improve rectifyHtml and some others

- packages/waku/src/lib/renderers/html-renderer.ts
> refactor: html renderer (detecting closing body)

- .gitignore
- e2e/07_router_standalone.spec.ts
- e2e/utils.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/handlers/dev-worker-impl.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
close #320
This issue exists in v0.18.1.
> fix: standalone 07_router example

- playwright.config.ts
> fix: remove parallel for each CI

- packages/waku/src/lib/handlers/dev-worker-api.ts
- packages/waku/src/lib/handlers/dev-worker-impl.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
> refactor: config type

- .github/workflows/cd.yml
- packages/create-waku/package.json
- packages/waku/package.json
https://docs.npmjs.com/generating-provenance-statements
https://github.blog/2023-04-19-introducing-npm-package-provenance/
> ci: support npm provenance

- examples/01_counter/tsconfig.json
- examples/02_async/src/components/App.tsx
- examples/02_async/tsconfig.json
- examples/03_promise/tsconfig.json
- examples/04_callserver/tsconfig.json
- examples/05_mutation/tsconfig.json
- examples/06_nesting/tsconfig.json
- examples/07_router/package.json
- examples/07_router/src/components/FooPage.tsx
- examples/07_router/src/entries.tsx
- examples/07_router/tsconfig.json
- examples/08_cookies/tsconfig.json
- examples/09_cssmodules/tsconfig.json
- examples/10_dynamicroute/tsconfig.json
- examples/11_form/tsconfig.json
- examples/12_css/tsconfig.json
- pnpm-lock.yaml
> chore: examples

- e2e/fixtures/rsc-basic/package.json
- e2e/fixtures/rsc-router/package.json
- e2e/fixtures/ssr-basic/package.json
- examples/01_counter/package.json
- examples/02_async/package.json
- examples/03_promise/package.json
- examples/04_callserver/package.json
- examples/05_mutation/package.json
- examples/06_nesting/package.json
- examples/07_router/package.json
- examples/08_cookies/package.json
- examples/09_cssmodules/package.json
- examples/10_dynamicroute/package.json
- examples/11_form/package.json
- examples/12_css/package.json
- package.json
- packages/waku/package.json
- packages/website/package.json
- pnpm-lock.yaml
the latest one is `20231219`. isn't it not updated lately?
> update react canary

- README.md
- packages/waku/package.json
- packages/waku/src/lib/handlers/dev-worker-api.ts
- packages/waku/src/lib/handlers/handler-dev.ts
and some minor fixes.
#324 requires Node.js >= 18.16.0
ref: https://github.com/nodejs/node/pull/45955
> chore: update node requirement

- e2e/fixtures/ssr-basic/src/entries.tsx
- examples/01_counter/src/entries.tsx
- examples/02_async/src/entries.tsx
- examples/03_promise/src/entries.tsx
- examples/04_callserver/src/entries.tsx
- examples/05_mutation/src/entries.tsx
- examples/06_nesting/src/entries.tsx
- examples/07_router/src/entries.tsx
- examples/08_cookies/src/entries.tsx
- examples/09_cssmodules/src/entries.tsx
- examples/11_form/src/entries.tsx
- examples/12_css/src/entries.tsx
- packages/waku/src/client.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/handlers/dev-worker-api.ts
- packages/waku/src/lib/handlers/dev-worker-impl.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/server.ts
- packages/waku/src/server.ts
It's a dev-only issue.
Re-implement getSsrConfig.
> fix: getSsrConfig (to work with server-only)

- examples/08_cookies/start.js
- package.json
- packages/waku/package.json
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/output-cloudflare.ts
- packages/waku/src/lib/builder/output-deno.ts
- packages/waku/src/lib/builder/output-vercel.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/middleware/connect-utils.ts
- packages/waku/src/lib/plugins/vite-plugin-nonjs-resolve.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/main.ts
- packages/waku/src/prd.ts
> bundle waku for deployment

- examples/07_router/src/entries.tsx
- packages/waku/src/router/server.ts
> fix(router): path handling createPages

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
(we should eventually add test cases for various config values.)
> fix: use config where appropriate

- e2e/fixtures/rsc-basic/package.json
- e2e/fixtures/rsc-router/package.json
- e2e/fixtures/ssr-basic/package.json
- examples/01_template/package.json
- examples/02_minimal/package.json
- examples/03_promise/package.json
- examples/04_callserver/package.json
- examples/05_mutation/package.json
- examples/06_nesting/package.json
- examples/07_router/package.json
- examples/08_cookies/package.json
- examples/09_cssmodules/package.json
- examples/10_dynamicroute/package.json
- examples/11_form/package.json
- examples/12_css/package.json
- examples/13_path-alias/package.json
- packages/waku/package.json
- pnpm-lock.yaml
fix a regression with #355 
close #371
> make RSDW a peer dependency

- packages/waku/src/main.ts
This adds `getEnv` to the main bundle.
> feat: consolidate imports

- examples/12_css/package.json
- examples/12_css/vite.config.ts
- pnpm-lock.yaml
> fix(examples): 12_css to prefer dev-only external workaround to commonjs plugin

- CHANGELOG.md
> fix a typo

- packages/create-waku/cli.js
- packages/create-waku/src/index.ts
- packages/waku/cli.js
- packages/waku/src/cli.ts
> chore: cli mode

- package.json
- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/output-vercel.ts
- packages/waku/src/lib/builder/serve-cloudflare.ts
- packages/waku/src/lib/builder/serve-deno.ts
- packages/waku/src/lib/builder/serve-vercel.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/lib/utils/node-fs.ts
- packages/waku/src/server.ts
- packages/website/package.json
- packages/website/src/entries.tsx
- packages/website/src/lib/load-readme.ts
- packages/website/src/templates/home-page.tsx
- pnpm-lock.yaml
following #433 
- serveStatic first
- simplify build & prd
- refactor vercel deploy
> serve static first

- packages/waku/src/router/client.ts
> router: do not refetch on popstate

- packages/waku/src/client.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/src/lib/renderers/utils.ts
> avoid url encoding for action id

- packages/waku/src/client.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
- packages/website/package.json
- pnpm-lock.yaml
This should handle waku/router better.
> fix: rsc-reload for waku/router

- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
> refactor: eliminate isBuild leftover

- packages/create-waku/package.json
- packages/create-waku/src/index.ts
npm simply ignore `.gitignore` file.
> fix(create-waku): handle .gitignore file

- examples/13_path-alias/src/components/App.tsx
- examples/13_path-alias/src/components/Counter.tsx
- examples/13_path-alias/src/components/MyFragment.tsx
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-analyze.ts
- add an error case that happened before #180
- refactor to eliminate `commonFileSet`
> refactor(build): eliminate common file set

- README.md
- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/output-partykit.ts
- packages/waku/src/lib/builder/serve-partykit.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
This adds experimental support for deploying to PartyKit (https://www.partykit.io/)
> feat: output partykit

- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/serve-cloudflare.ts
- packages/waku/src/lib/builder/serve-partykit.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
> chore: refactor builder

- packages/waku/src/router/client.ts
- packages/website/package.json
- pnpm-lock.yaml
This is technically a breaking change, but it's more importantly a fix.
I'm not really sure how to deal with location.hash for components, but it's something server would never know, so basically we don't care. we will see if it causes any troubles.
> fix(router): support location hash

- examples/07_router/src/entries.tsx
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/defineRouter.ts
> support 404 for waku/router

- e2e/fixtures/rsc-basic/src/components/Box.tsx
- packages/waku/src/router/client.ts
- packages/waku/src/router/defineRouter.ts
- packages/website/package.json
- pnpm-lock.yaml
and make a function to arrow, and fixing website vercel deploy.
follow up #501
> refactor: PropsWithChildren

- packages/waku/src/lib/renderers/html-renderer.ts
https://github.com/dai-shi/waku/pull/518#discussion_r1500269036
`npm run examples:prd:04_promise`
> follow-up #518 and fix an error in PRD

- .eslintrc.json
https://github.com/DRD4-7R/eslint-config-7r-building/issues/1#issuecomment-779443161
> fix: stop eslint react warning

- docs/builder/aws-lambda.mdx
Documentation of a minimal setup to deploy WAKU to AWS Lambda.
> docs: add AWS Lambda builder

- .eslintrc.json
- e2e/fixtures/rsc-basic/src/components/ServerPing/Counter.tsx
- packages/waku/src/cli.ts
- packages/waku/src/client.ts
- packages/waku/src/lib/builder/serve-vercel.ts
- packages/waku/src/lib/handlers/dev-worker-api.ts
- packages/waku/src/lib/handlers/dev-worker-impl.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- tsconfig.eslint.json
It looks like the floating promise caused this issue. I will enable this rule by default.
Discussion: https://github.com/dai-shi/waku/issues/543#issuecomment-1965866167
If you miss a promise, then there's an undefined behavior I guess (I cannot find the document about what if)
> fix: enable no floating promise

- packages/waku/src/client.ts
This fixes the first issue: https://github.com/dai-shi/waku/issues/539#issuecomment-1963668947
> fix: useRefetch

- e2e/fixtures/rsc-basic/src/entries.tsx
- packages/waku/package.json
- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/serve-aws-lambda.ts
- packages/waku/src/lib/builder/serve-cloudflare.ts
- packages/waku/src/lib/builder/serve-deno.ts
- packages/waku/src/lib/builder/serve-netlify.ts
- packages/waku/src/lib/builder/serve-partykit.ts
- packages/waku/src/lib/builder/serve-vercel.ts
- packages/waku/src/lib/handlers/handler-dev.ts
- packages/waku/src/lib/handlers/handler-prd.ts
- packages/waku/src/lib/hono/runner.ts
- packages/waku/src/lib/middleware/dev-server.ts
- packages/waku/src/lib/middleware/fallback.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/middleware/ssr.ts
- packages/waku/src/lib/middleware/types.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
- packages/waku/src/lib/renderers/dev-worker-api.ts
- packages/waku/src/lib/renderers/dev-worker-impl.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/src/middleware.ts
- packages/waku/src/middleware/dev-server.ts
- packages/waku/src/middleware/fallback.ts
- packages/waku/src/middleware/rsc.ts
- packages/waku/src/middleware/ssr.ts
- packages/waku/src/server.ts
step 1 for #513 following #545
> step 2 for middleware architecture

- examples/05_actions/src/components/funcs.ts
- examples/08_cookies/src/components/App.tsx
- examples/08_cookies/src/entries.tsx
- examples/11_form/src/components/funcs.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/middleware/ssr.ts
- packages/waku/src/lib/renderers/dev-worker-impl.ts
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/src/server.ts
> feat: `getContext` & `rerender`

- packages/waku/src/lib/config.ts
- packages/waku/src/lib/renderers/html-renderer.ts
> fix: html renderer in DEV

- e2e/fixtures/rsc-router/src/entries.tsx
- packages/waku/src/router/create-pages.ts
- packages/waku/src/router/define-router.ts
but it's behavior is hard to explain...
> feat(router): support dynamic layout

- examples/12_css/package.json
- examples/12_css/src/components/App.tsx
- examples/12_css/src/type.d.ts
- examples/12_css/vite.config.ts
- pnpm-lock.yaml
I think 0.19.4 fix many compatibility issue
Fixes: https://github.com/dai-shi/waku/issues/455
> chore: bump 12_css example

- packages/waku/src/router/client.ts
There was another regression in #593.
> fix(router): fix shouldSkip with stable module state

- packages/waku/src/router/client.ts
- packages/waku/src/router/define-router.ts
> fix(router): scroll after route change

- examples/07_router/src/components/Counter.tsx
- packages/waku/src/main.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/define-router.ts
with `_UNSTABLE` suffix.
removed: `useLocation` and `useChangeLocation`. (BREAKING)
> feat(router): useRouter

- packages/waku/package.json
- packages/waku/src/main.react-server.ts
- packages/waku/src/main.ts
to fix the weird console.log error in the browser.
> separate main entry point with react-server condition

- packages/waku/src/router/client.ts
A signature change right after the v0.20.0 release. 😄
> fix(router/client): useRouter returns properties of value

- examples/24_nesting/src/components/Counter.tsx
Hey! In this Pull Request, I have simply deleted a redundant condition as it is already checked a few lines above.
> chore(example): remove useless condition

- examples/10_fs-router/src/entries.tsx
- packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts
Nobody told me that it was possible. 😄
> refactor: use import.meta.glob

- packages/waku/src/router/fs-router.ts
> fix(fs-router): build with catch-all pages

- examples/12_css/src/components/App.tsx
- examples/12_css/src/components/ClientBanner.tsx
- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
repro with `vite-plugin-stylex-dev`
> fix: transforming client components

- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
> fix: css modules with hmr

- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
> fix: FOUC with CSS Modules (RSC only)

- e2e/07_router_standalone.spec.ts
- e2e/examples-smoke.spec.ts
- e2e/rsc-basic.spec.ts
- e2e/rsc-router.spec.ts
- e2e/ssr-basic.spec.ts
- e2e/ssr-context-provider.spec.ts
- e2e/ssr-swr.spec.ts
- e2e/ssr-target-bundle.spec.ts
- packages/waku/src/lib/middleware/dev-server.ts
- packages/waku/src/lib/renderers/dev-worker-impl.ts
Since we have managed mode, `entries.tsx` file might not exist.
> fix: vite optimize deps

- docs/community/examples.mdx
This example is an example of adding yarn's zero installation to the waku framework,
which is directly used by the company you work with in this same structure, and made PR to share.
> docs: update example (yarn pnp)

- packages/waku/src/router/client.ts
Looks like there was a regression in #613.
> fix(router): push state on redirect

- packages/waku/src/config.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-serve.ts
- packages/waku/src/lib/renderers/html-renderer.ts
and includes a small refactor in rscIndex plugin.
> experimental support for customizing html attributes

- e2e/fixtures/ssg-wildcard/tsconfig.json
to be consistent with others
(being not sure if it's the ideal tsconfig for e2e though.)
> chore: e2e tsconfig

- e2e/fixtures/partial-build/package.json
- e2e/fixtures/render-type/package.json
- e2e/fixtures/rsc-basic/package.json
- e2e/fixtures/rsc-css-modules/package.json
- e2e/fixtures/rsc-router/package.json
- e2e/fixtures/ssg-performance/package.json
- e2e/fixtures/ssg-wildcard/package.json
- e2e/fixtures/ssr-basic/package.json
- e2e/fixtures/ssr-context-provider/package.json
- e2e/fixtures/ssr-swr/package.json
- e2e/fixtures/ssr-target-bundle/package.json
- examples/01_template/package.json
- examples/02_template_js/package.json
- examples/03_demo/package.json
- examples/04_cssmodules/package.json
- examples/07_router/package.json
- examples/08_cookies/package.json
- examples/10_fs-router/package.json
- examples/11_form/package.json
- examples/12_css/package.json
- examples/13_path-alias/package.json
- examples/14_react-tweet/package.json
- examples/20_minimal/package.json
- examples/21_minimal_js/package.json
- examples/22_promise/package.json
- examples/23_actions/package.json
- examples/24_nesting/package.json
- packages/waku/package.json
- packages/website/package.json
- pnpm-lock.yaml
Upstream: https://github.com/facebook/react/pull/29060
> chore: bump to `react@19-rc`

- packages/waku/src/lib/utils/merge-vite-config.ts
> fix: merging vite plugins

- packages/waku/src/lib/utils/merge-vite-config.ts
> fix: merging vite plugins 2

- packages/waku/src/client.ts
follow up #708 which wasn't enough. related: #714
> refactor waku/client 2

- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
> refactor: rscTransform plugin

- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
#708 changed the code, but type check doesn't work for this code.
It would be nice to have a better way somehow.
> fix: server hot reload (with #708)

- packages/waku/src/client.ts
> fix: refetch transition

- packages/waku/src/client.ts
- packages/waku/src/router/client.ts
> fix(client): avoid try-catch for use

- packages/waku/src/router/client.ts
> fix(router): use startTransition

- examples/03_demo/src/pages/index.tsx
> fix: demo source link

- .github/workflows/ci.yml
- packages/waku/tests/vite-plugin-rsc-analyze.test.ts
> fix(test): hack crypto in vitest

- packages/waku/src/lib/middleware/dev-server.ts
- packages/waku/src/lib/middleware/ssr.ts
- packages/waku/src/lib/middleware/types.ts
- packages/waku/src/lib/renderers/dev-worker-impl.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
I'm planning to change something and to reduce the diff, this is a small refactor.
> refactor: vite dev server main/rsc

- packages/waku/src/lib/renderers/html-renderer.ts
https://github.com/dai-shi/waku/pull/745/files#r1646856945
> chore(types): simplify type in html-renderer

- examples/23_actions/vite.config.ts
Not exactly sure which PR made it possible. #762 or #764? or?
> chore(examples): remove unnecessary vite config

- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
This is too add one more test case for inline "use server".
I will work on a new impl in a separate pr and hopefully cover 👇 .
- ~support vercel/ai/rsc https://github.com/dai-shi/waku/pull/745/files#r1644045238~
- ~remove "use server" directive after transformation?~
> chore(tests): add inline "use server" use cases

- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
> fix: server action transformation with `.bind`

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Upstream: https://github.com/pnpm/action-setup/issues/135#issuecomment-2206861174
> ci: update pnpm setup

- examples/11_form/src/components/App.tsx
- examples/11_form/src/components/Form.tsx
- examples/11_form/src/components/funcs.ts
- examples/23_actions/src/components2/App.tsx
- examples/23_actions/src/components2/funcs.ts
https://github.com/dai-shi/waku/pull/774#issuecomment-2208078428
> chore(examples): make all server functions async

- packages/website/vite.config.ts
Hmm, this is going to be a big problem with ESM/CJS compat...
Maybe related: #421, #428
> fix(website): hack next-mdx-remote with vite config (DEV only)

- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
Adding some tests before working on #777.
> chore(tests): more tests for rscTransform

- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
I gave up the previous runtime solution and did a compiler solution which supports only limited patterns.
> fix: transform server action (not twice)

- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
> fix: support default export server action

- packages/waku/src/lib/middleware/dev-server.ts
- packages/waku/src/router/fs-router.ts
It was my misunderstanding to remove `@vite-ignore` in #792.
Thanks to @Aslemammad https://github.com/dai-shi/waku/pull/798/files#r1687432289
> chore: revert vite-ignore

- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/middleware/ssr.ts
- packages/waku/src/lib/middleware/types.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-rsdw.ts
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
and make naming somewhat consistent.
> refactor(dev-server): combine loadServerFile and loadServerModule

- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/middleware/ssr.ts
- packages/waku/src/lib/middleware/types.ts
This is the first step to hide `willBeHandledLater` from `ctx.devServer`.
> refactor(dev): avoid willBeHandledLater

- docs/guides/stream-intercept.mdx
- examples/08_cookies/waku.config.ts
- examples/09_api/waku.config.ts
- package.json
- packages/waku/src/cli.ts
- packages/waku/src/config.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/hono/runner.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/middleware/fallback.ts
- packages/waku/src/lib/middleware/ssr.ts
following up #809.
This is still incomplete and need more refactors as noted in `FIXME`.
> fix: not found in DEV and refactor fallback handling

- packages/waku/src/lib/hono/runner.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
> fix(hono/runner): check status in addition to non-empty body

- packages/waku/package.json
> chore: do not publish src

- e2e/fixtures/partial-build/package.json
- e2e/fixtures/render-type/package.json
- e2e/fixtures/rsc-basic/package.json
- e2e/fixtures/rsc-css-modules/package.json
- e2e/fixtures/rsc-router/package.json
- e2e/fixtures/ssg-performance/package.json
- e2e/fixtures/ssg-wildcard/package.json
- e2e/fixtures/ssr-basic/package.json
- e2e/fixtures/ssr-catch-error/package.json
- e2e/fixtures/ssr-context-provider/package.json
- e2e/fixtures/ssr-swr/package.json
- e2e/fixtures/ssr-target-bundle/package.json
- e2e/fixtures/use-router/package.json
- pnpm-lock.yaml
to use caret version if possible.
> chore(fixtures): package.json

- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/utils/vite-loader.ts
copying the fix in #788.
most work done by @Aslemammad.
> fix(dev-server): initial modules recursive resolution and module loading in ssr

- packages/waku/src/client.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/middleware/rsc.ts
- packages/waku/src/lib/middleware/ssr.ts
- packages/waku/src/lib/renderers/html-renderer.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/src/lib/renderers/utils.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/common.ts
- packages/waku/src/router/define-router.ts
- packages/waku/src/server.ts
another take for #832, which is reverted in `main`.
> feat: redesign RSC protocol again

- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
- packages/waku/src/router/client.ts
I forgot to change this in #835. TS doesn't work for strings 😓 .
> fix: hot reload rsc

- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/website/vite.config.ts
avoid "new dependencies optimized" messages from vite.
> fix(dev): optimize deps

- e2e/fixtures/ssr-basic/package.json
- e2e/fixtures/ssr-basic/src/ai/index.ts
- e2e/fixtures/ssr-basic/src/components/AIClient.tsx
- e2e/fixtures/ssr-basic/src/components/App.tsx
- e2e/fixtures/ssr-basic/tsconfig.json
- e2e/fixtures/ssr-basic/vite.config.ts
- e2e/ssr-basic.spec.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- pnpm-lock.yaml
Upstream: https://github.com/dai-shi/waku/pull/788
> test: add vercel ai fixtures

- examples/23_actions/src/components2/TextBox.tsx
- examples/23_actions/src/components2/funcs2.ts
> chore(examples): add bind usage

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-rsdw.ts
- packages/waku/src/lib/renderers/html-renderer.ts
While working on #841, I noticed it's a valid hack for now. So, simplified a little bit.
> refactor: vite-plugin-rsc-rsdw and related stuff

- packages/waku/package.json
- pnpm-lock.yaml
> downgrade swc/core

- packages/waku/src/lib/builder/build.ts
> fix(build): do not remove index.html when buildConfig is empty

- examples/24_nesting/src/components/Counter.tsx
- examples/24_nesting/src/components/InnerApp.tsx
- packages/waku/src/client.ts
> fix(client): do not wrap with `startTransition`

- packages/waku/src/lib/middleware/rsc.ts
> fix: rsc middleware

- packages/waku/src/router/create-pages.ts
#799 changed something and this is a leftover.
> fix(router): fix types

- packages/waku/src/cli.ts
- packages/waku/src/config.ts
- packages/waku/src/lib/config.ts
> add: unstable_honoEnhancer in config

- examples/14_react-tweet/src/entries.tsx
Changing this example to match returning the list of pages
> fix: createPages use in react tweet example

- packages/waku/src/cli.ts
- packages/waku/src/config.ts
https://github.com/dai-shi/waku/discussions/915#discussioncomment-10787569
> feat: unstable_honoEnhancer to be more flexible

- packages/waku/src/cli.ts
- packages/waku/src/lib/hono/engine.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts
- packages/waku/src/unstable_hono.ts
> refactor: rename hono runner

- packages/waku/src/lib/middleware/dev-server-impl.ts
Fixes: https://github.com/dai-shi/waku/issues/930
> fix: dev server on windows

- packages/waku/src/lib/hono/ctx.ts
- packages/waku/src/lib/hono/engine.ts
- packages/waku/src/unstable_hono.ts
> refactor: unstable_hono

- packages/waku/src/router/client.ts
https://github.com/dai-shi/waku/pull/931#discussion_r1787027823
> revert router/client change in #931

- docs/minimal-api.mdx
- examples/07_router/src/entries.tsx
- examples/11_form/src/entries.tsx
- examples/13_path-alias/src/entries.tsx
- examples/22_promise/src/entries.tsx
- examples/25_weave_render/src/entries.tsx
https://github.com/dai-shi/waku/pull/922#discussion_r1786235548
> docs: remove lazy import from examples

- .eslintrc.json
Fixes: https://github.com/dai-shi/waku/issues/954
> chore: update eslint ignore

- e2e/fixtures/broken-links/public/serve.json
- e2e/fixtures/ssr-catch-error/src/middleware/validator.ts
- e2e/partial-builds.spec.ts
- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/src/lib/renderers/rsc-renderer.ts
- packages/waku/src/lib/renderers/utils.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/common.ts
- packages/waku/src/router/define-router.ts
- packages/waku/tests/rscPath.test.ts
> redesign rscPath encoding

- .eslintrc.json
- examples/03_demo/src/pages/[slug].tsx
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- packages/website/src/components/analytics.tsx
- packages/website/src/components/credits.tsx
- packages/website/src/components/sponsors.tsx
- packages/website/src/pages/blog/[slug].tsx
follow up to: https://github.com/dai-shi/waku/pull/952#discussion_r1789346977
> chore: lint for curly brackets and fix

- .github/actions/playwright/action.yml
Fixes: https://github.com/dai-shi/waku/pull/883#issuecomment-2402730271
Refs: https://github.com/microsoft/playwright/issues/7249#issuecomment-2301568516
> ci: playwright cache for Windows/macOS

- packages/create-waku/package.json
- pnpm-lock.yaml
oops, I forgot to keep the ncc version. the previous one: #938
> fix(create-waku): downgrade ncc

- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
I didn't notice this case until reported.
> fix(rsc-transform): fix server function error in SSR

- .github/workflows/ci.yml
- packages/waku/src/lib/utils/buffer.ts
- packages/waku/tests/buffer.test.ts
- packages/waku/tests/vite-plugin-rsc-analyze.test.ts
#945 wasn't enough. cc @himself65
> run tests on all node versions

- .gitignore
this is the playwright output locally
> chore: gitignore test-results

- packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts
Follow up to #923. I need to test these three but should be able to...
> feat: honoEnhancer for Vercel, Deno and Netlify

- packages/waku/tests/buffer.test.ts
> chore(tests): detect node version precisely

- packages/waku/src/router/client.ts
Previously with current Router, this issue wasn't revealed because of other bugs (?), but this change should be reasonable. (I'm not happy with the current overall implementation. Hope to revisit.)
> fix: NewRouter for unstable_defineRouter

- packages/waku/src/minimal/client.ts
- packages/waku/src/router/create-pages.ts
> fix: fallback support with ErrorContext

- examples/22_define-router/src/components/HomeLayout.tsx
- examples/22_define-router/src/entries.tsx
- packages/waku/src/router/define-router.ts
> chore(examples): 22_define-router

- e2e/hot-reload.spec.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-delegate.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
#1021 was incomplete. This should fix it.
> fix: improve client HMR

- e2e/fixtures/render-type/src/main.tsx
- e2e/fixtures/rsc-router/src/entries.tsx
- e2e/fixtures/rsc-router/src/main.tsx
- examples/11_fs-router/src/main.tsx
- examples/21_create-pages/src/main.tsx
- examples/22_define-router/src/entries.tsx
- examples/22_define-router/src/main.tsx
- examples/42_react-tweet/src/main.tsx
- examples/43_weave-render/src/main.tsx
- packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/create-pages.ts
- packages/waku/src/router/define-router.ts
- packages/waku/src/router/server.ts
- packages/waku/tests/create-pages.test.ts
will come after #1039 
- `new_defineRouter` 👉 `unstable_defineRouter`
- `NewRouter` 👉 `Router`
> chore(router): replace unstable_defineRouter and Router with new versions

- packages/waku/src/router/fs-router.ts
Resolves runtime error caused by removing a page file when running the dev server with fs-router projects
> fix(hmr): file add and delete runtime error with fs-router

- examples/21_create-pages/src/components/Counter.tsx
> chore(examples): useTransition in 21_create-pages example

- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-rsdw.ts
- ~external/noExternal in loadServerModuleMain~
> fix: module loading in DEV

- docs/guides/cloudflare.mdx
Remove a few references to the old Cloudflare Pages implementation.
> docs: cloudflare guide enhancement

- .github/workflows/canary-ci.yml
- .github/workflows/ci.yml
https://github.com/dai-shi/waku/pull/1047/files#r1875745448
does this work?
> chore: canary-ci

- .github/workflows/ci.yml
> fix(workflow): canary-ci yaml

- e2e/fixtures/hot-reload/src/pages/about.tsx
- e2e/fixtures/hot-reload/src/pages/index.tsx
- e2e/hot-reload.spec.ts
- package.json
- packages/waku/src/lib/plugins/vite-plugin-rsc-hmr.ts
There was an issue with router.
> fix(dev): hot-reload

- e2e/21_create-pages_standalone.spec.ts
- examples/11_fs-router/src/pages/nested/_layout.tsx
- examples/21_create-pages/src/components/NestedLayout.tsx
- examples/21_create-pages/src/entries.tsx
- packages/waku/src/router/create-pages.ts
- packages/waku/tests/create-pages.test.ts
> fix(create-pages): nested layouts missing

- packages/waku/src/lib/middleware/dev-server-impl.ts
> fix(dev): waku package not found

- packages/waku/src/lib/middleware/dev-server-impl.ts
and optimize deps config.
kind of following up #1064.
> refactor(dev-server): load server module main

- examples/36_form/src/entries.tsx
- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/lib/renderers/html.ts
- packages/waku/src/lib/renderers/rsc.ts
- packages/waku/src/lib/types.ts
- packages/waku/src/router/define-router.ts
- packages/waku/src/types.d.ts
> feat: progressive enhancement for form actions

- packages/waku/src/lib/builder/build.ts
following up #1043.
If this doesn't work we need to look for completely alternative approaches:
- bundle middleware in dist
- use custom ALS in define-router
> fix(define-router): context for build

- e2e/21_create-pages_standalone.spec.ts
- examples/21_create-pages/src/components/funcs.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/hono/ctx.ts
- packages/waku/src/lib/middleware/context.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/router/define-router.ts
- packages/waku/src/server.ts
> fix(build): avoid externalizing waku/middleware/context

- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/lib/utils/stream.ts
It gives a chance for non async components to write to context or something.
It's pretty limited and I'm not sure if we keep this feature in the future.
> fix(handler): wait for first chunk in stream

- e2e/21_create-pages_standalone.spec.ts
- examples/21_create-pages/src/entries.tsx
- packages/waku/src/router/create-pages.ts
needed to lookup the wildcard page component
e2e test added to check
> fix(create-pages): dynamic wildcard pages runtime errored

- docs/guides/monorepo.mdx
Let's improve this guide together.
> docs: add minimal monorepo guide

- packages/waku/src/router/create-pages.ts
- packages/waku/src/router/define-router.ts
- packages/waku/tests/create-pages.test.ts
> refactor: define-router

- examples/37_css/package.json
- examples/37_css/src/components/ClientBanner.tsx
- examples/37_css/src/components/app.css
- examples/37_css/src/components/banner.tsx
- examples/37_css/vite.config.ts
- pnpm-lock.yaml
> fix: stylex example to use new vite plugin

- .github/workflows/cd.yml
- .github/workflows/ci.yml
* update `actions/setup-node` and `actions/upload-artifact`
> chore(.github/workflows): update action version used in 'uses'

- examples/35_nesting/src/entries.tsx
https://github.com/dai-shi/waku/pull/1093#discussion_r1900287722
> fix(examples): fix typo

- examples/51_spa/package.json
- examples/51_spa/src/components/App.tsx
- examples/51_spa/src/components/Counter.tsx
- examples/51_spa/src/entries.tsx
- examples/51_spa/src/functions/greet.tsx
- examples/51_spa/src/main.tsx
- examples/51_spa/tsconfig.json
- examples/51_spa/waku.config.ts
- packages/waku/src/lib/builder/build.ts
- pnpm-lock.yaml
ref: https://x.com/dai_shi/status/1876501122078372340
> example: 51_spa

- packages/waku/tests/create-pages.test.ts
simple tests for static and dynamic uses of createApi
> test(create-pages): unit test createApi static and dynamic

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/server.ts
> fix(build): fsRouterFiles were not included during static build

- e2e/create-pages.spec.ts
- e2e/define-router.spec.ts
- e2e/fixtures/define-router/src/entries.tsx
createPages and defineRouter e2e api handling tests now match
> test: defineRouter tests for e2e with fetch and post

- .github/workflows/e2e.yml
- .github/workflows/test.yml
- packages/waku/src/router/create-pages.ts
> router: make createApi experimental

- .github/workflows/canary-ci.yml
- .github/workflows/test.yml
some of #1153 were my bad changes.
> fix: github workflow for canary-ci again

- .github/workflows/canary-ci.yml
> fix: github workflow for canary-ci 3

- e2e/fixtures/fs-router/package.json
- e2e/fixtures/fs-router/private/hi.txt
- e2e/fixtures/fs-router/src/components/Counter.tsx
- e2e/fixtures/fs-router/src/pages/_layout.tsx
- e2e/fixtures/fs-router/src/pages/_root.tsx
- e2e/fixtures/fs-router/src/pages/api/empty.ts
- e2e/fixtures/fs-router/src/pages/api/hi.ts
- e2e/fixtures/fs-router/src/pages/api/hi.txt.ts
- e2e/fixtures/fs-router/src/pages/bar.tsx
- e2e/fixtures/fs-router/src/pages/foo/index.tsx
- e2e/fixtures/fs-router/src/pages/index.tsx
- e2e/fixtures/fs-router/src/pages/nested/[name].tsx
- e2e/fixtures/fs-router/src/pages/nested/_layout.tsx
- e2e/fixtures/fs-router/tsconfig.json
- e2e/fs-router.spec.ts
- e2e/utils.ts
- pnpm-lock.yaml
- tsconfig.e2e.json
I need help with how to correctly set `VITE_EXPERIMENTAL_WAKU_ROUTER=true` on this PR
> test(fs-router): e2e test with api tests

- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- packages/waku/tests/vite-plugin-fs-router-typegen.test.ts
- packages/website/private/contents/post-006.mdx
fixes: [discord comment](https://discord.com/channels/627656437971288081/1083774812129857566/1330093730354561034)
fixes #1148
related to #1163
> fix(typegen): skip parsing errors and remove formatting

- e2e/fixtures/ssr-basic/package.json
- e2e/utils.ts
- examples/37_css/package.json
- examples/38_cookies/package.json
- examples/44_cloudflare/package.json
- packages/waku/package.json
- packages/website/package.json
- pnpm-lock.yaml
and tweak e2e/utils.ts to ignore some known errors.
> chore(deps): update dependencies

- packages/website/vercel.json
adding headers for RSC payloads
> chore(website): vercel.json

- package.json
- packages/website/package.json
and also move the flag from packages/website/package.json
> fix: scripts for vite-ecosystem-ci

- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
this removes the unused lint disable comment warning
> fix: Remove eslint disable

- e2e/examples-smoke.spec.ts
Run the cloudflare example e2e smoke test with wrangler / workerd runtime.
Re: #1178
> test: workerd e2e smoke test

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-analyze.ts
- packages/waku/tests/vite-plugin-rsc-analyze.test.ts
> fix(core): add hash to rsf{n}

- e2e/fixtures/rsc-basic/src/components/ClientCounter.tsx
- e2e/rsc-basic.spec.ts
- examples/22_define-router/src/components/HomeLayout.tsx
- packages/waku/src/lib/middleware/dev-server-impl.ts
> fix(minimal/dev): rscPath encoding in willBeHandled

- e2e/utils.ts
Fixes: https://github.com/dai-shi/waku/issues/1213
> fix(e2e): use pnpmOverrides

- examples/07_cloudflare/package.json
- examples/07_cloudflare/postcss.config.js
- examples/07_cloudflare/vite.config.ts
- pnpm-lock.yaml
> fix(cloudflare): use postcss for example

- examples/07_cloudflare/src/lib/hono.ts
- examples/07_cloudflare/src/pages/index.tsx
- examples/07_cloudflare/waku.cloudflare-middleware.ts
- examples/07_cloudflare/waku.config.ts
> Fix response streaming with wrangler dev server

- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- packages/waku/src/lib/utils/fs-router.ts
- packages/waku/src/lib/utils/path.ts
- packages/waku/src/router/fs-router.ts
> fix(router): _components and _hooks should be ignored by path typegen

- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/lib/renderers/utils.ts
- packages/waku/src/lib/utils/custom-errors.ts
- packages/waku/src/minimal/client.ts
> feat: handle custom errors

- e2e/create-pages.spec.ts
- e2e/fixtures/create-pages/src/components/HomeLayout.tsx
- e2e/fixtures/create-pages/src/components/LongSuspenseLayout.tsx
- e2e/fixtures/create-pages/src/entries.tsx
- e2e/fixtures/define-router/src/routes/layout.tsx
- e2e/fixtures/fs-router/src/pages/_layout.tsx
- examples/11_fs-router/src/pages/_layout.tsx
- examples/21_create-pages/src/components/HomeLayout.tsx
- examples/22_define-router/src/components/HomeLayout.tsx
- examples/43_weave-render/src/components/BarLayout.tsx
- examples/43_weave-render/src/components/HomeLayout.tsx
- packages/waku/src/router/client.ts
> fix(router): avoid default startTransition

- e2e/fixtures/define-router/tsconfig.json
- e2e/fixtures/hot-reload/declaration.d.ts
- e2e/fixtures/hot-reload/src/pages/css-modules.module.css
- e2e/fixtures/hot-reload/src/pages/css-modules.tsx
- e2e/fixtures/hot-reload/tsconfig.json
- e2e/fixtures/render-type/tsconfig.json
- e2e/fixtures/rsc-asset/tsconfig.json
- e2e/fixtures/rsc-basic/tsconfig.json
- e2e/fixtures/rsc-css-modules/tsconfig.json
- e2e/fixtures/ssg-performance/tsconfig.json
- e2e/hot-reload.spec.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-delegate.ts
- pnpm-lock.yaml
> fix(dev-server): hot reload with css modules

- packages/waku/src/router/client.ts
- packages/waku/src/router/define-router.ts
- packages/waku/src/router/server.ts
follow up #1247
experimental router api for #1239
> fix(router): experimental custom error handler

- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/plugins/hack-tailwindcss4-stackblitz.ts
> hack tailwindcss4 for stackblitz

- packages/waku/src/lib/utils/create-pages.ts
🤫
heads up @rmarscher this will be marked stable with 0.22, for now it needs the flag.
> chore(router): flag route groups feature

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/hono/engine.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/middleware/fallback.ts
- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/lib/renderers/html.ts
- packages/waku/src/lib/utils/vite-config.ts
> refactor: rename to config dev

- README.md
close https://github.com/dai-shi/waku/issues/1286
> Tailwind configuration update version 4 (README: Styling/Global styles)

- packages/waku/src/cli.ts
- packages/waku/src/lib/utils/vite-loader.ts
> refactor: vite-loader util

- examples/11_fs-router/src/entries.tsx
- examples/12_nossr/src/entries.ts
- packages/waku/src/config.ts
- packages/waku/src/lib/config.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts
- packages/waku/src/router/fs-router.ts
> feat(router): fs-router support apiDir configurability

- packages/waku/src/lib/plugins/vite-plugin-rsc-rsdw.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
This may slow down a bit though.
> generate source maps in plugins

- packages/waku/src/server.ts
Sorry I missed this in a previous review.
> fix: unstable_emitPlatformData export typo

- packages/waku/src/config.ts
- packages/waku/src/lib/builder/build.ts
I think we need this for #1279
> feat: extend build-deploy vite config

- .codesandbox/ci.json
- docs/guides/docker.mdx
- packages/waku/src/lib/builder/build.ts
- packages/waku/tests/vite-plugin-rsc-analyze.test.ts
> chore: cleanup after dropping support for node@18

- packages/waku/package.json
- pnpm-lock.yaml
> rollup 4.38.0

- packages/website/src/components/meta.tsx
adding rss.xml link to the head tag for ease of finding.
> feat(website): add rss feed link to head

- README.md
> docs(api): document api routes in the readme

- e2e/fixtures/create-pages/src/components/DeeplyNestedLayout.tsx
- e2e/fixtures/create-pages/src/components/ErrorBoundary.tsx
- e2e/fixtures/create-pages/src/components/NestedLayout.tsx
- e2e/fixtures/fs-router/src/pages/nested/_layout.tsx
- examples/07_cloudflare/src/components/counter.tsx
- examples/11_fs-router/src/pages/nested/_layout.tsx
- examples/21_create-pages/src/components/DeeplyNestedLayout.tsx
- examples/21_create-pages/src/components/NestedLayout.tsx
- packages/website/src/hooks/index.ts
> chore: avoid React namespace in types

- examples/01_template/package.json
- examples/02_template_js/package.json
- examples/03_demo/package.json
- examples/05_compiler/package.json
- examples/06_form-demo/package.json
- examples/07_cloudflare/package.json
- examples/12_nossr/package.json
- examples/42_react-tweet/package.json
- packages/website/package.json
- pnpm-lock.yaml
https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.1.1
> chore: bump tailwind with fix for @import included from 4.1.1

- examples/38_cookies/src/middleware/noop.ts
- examples/38_cookies/waku.config.ts
- packages/waku/src/lib/utils/vite-loader.ts
> fix: loading two middleware in DEV

- tsconfig.json
> chore: remove unused tsconfig paths

- packages/create-waku/package.json
- packages/create-waku/src/tests/cli-with-args.test.ts
change to faster installer for tests with pnpm instead of npm
> test: change cli installer to pnpm

- packages/create-waku/src/tests/cli-with-args.test.ts
https://github.com/vitejs/vite-ecosystem-ci/actions/runs/14395939973/job/40371526794
> chore(test): increase timeout

- e2e/broken-links.spec.ts
- e2e/create-pages.spec.ts
- e2e/fixtures/broken-links/src/components/ClientTitle.tsx
- e2e/fixtures/broken-links/src/pages/404.tsx
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts
- packages/waku/src/lib/types.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/define-router.ts
> fix: 404 handling

- e2e/fixtures/rsc-basic/src/components/App.tsx
- e2e/fixtures/rsc-basic/src/components/ClientCounter.tsx
- e2e/fixtures/rsc-basic/src/entries.tsx
- e2e/rsc-basic.spec.ts
- packages/waku/src/minimal/client.ts
#1354 fixed with only server functions. This is for server components.
> fix: temporary references with server components

- examples/08_jotai-demo/src/lib/waku-jotai/client.tsx
- examples/21_create-pages/src/components/RoutingHandler.tsx
- examples/35_nesting/src/components/Counter.tsx
- examples/53_islands/src/main.tsx
- examples/54_jotai/src/lib/waku-jotai/client.tsx
- packages/waku/src/minimal/client.ts
- packages/waku/src/router/client.ts
I think these help the cause. @tylersayshi
> #1391 routing events updates

- e2e/fixtures/rsc-basic/modules/ai/package.json
- examples/33_promise/src/components/Counter.tsx
- packages/waku/src/minimal/client.ts
found it there: https://github.com/wakujs/waku/pull/1393#discussion_r2062744570
> chore: eliminate canary things

- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/tests/vite-plugin-rsc-transform-internals.test.ts
Thanks to @hi-ogawa suggestion.
> fix: remove unnecessary enforce=pre in transform plugin

- examples/01_template/tsconfig.json
- examples/03_demo/tsconfig.json
- examples/04_cssmodules/tsconfig.json
- examples/05_compiler/tsconfig.json
- examples/06_form-demo/tsconfig.json
- examples/07_cloudflare/tsconfig.json
- examples/08_jotai-demo/tsconfig.json
- examples/11_fs-router/tsconfig.json
- examples/12_nossr/tsconfig.json
- examples/21_create-pages/tsconfig.json
- examples/22_define-router/tsconfig.json
- examples/31_minimal/tsconfig.json
- examples/33_promise/tsconfig.json
- examples/34_functions/tsconfig.json
- examples/35_nesting/tsconfig.json
- examples/36_form/tsconfig.json
- examples/37_css/tsconfig.json
- examples/38_cookies/tsconfig.json
- examples/39_api/tsconfig.json
- examples/41_path-alias/tsconfig.json
- examples/42_react-tweet/tsconfig.json
- examples/43_weave-render/tsconfig.json
- examples/45_view-transitions/tsconfig.json
- examples/51_spa/tsconfig.json
- examples/52_tanstack-router/tsconfig.json
- examples/53_islands/tsconfig.json
- examples/54_jotai/tsconfig.json
this adds sane defaults for our example tsconfig
ref: https://www.totaltypescript.com/tsconfig-cheat-sheet
fixes #1404
> fix(tsconfig): isolate modules

- packages/waku/src/cli.ts
This PR introduces a workaround for issue #756.
I've also been facing the same issue often.
Please look at 00:35 to observe the error.
I just added new lines to the file, then restarted the process.
https://github.com/user-attachments/assets/bf6b038c-10b9-435a-b85c-97651fc7b24e
It seems that the error comes from TransformStream, but all of the code seems to have no issue, and it's too hard to investigate.
However, as you can see in the above video, the error might be ignorable.
My suggestion is to catch the error and ignore it in only the dev CLI.
https://github.com/user-attachments/assets/4964197e-7594-49ab-a71f-c8398f25e168
You can see the result at 00:42.
> fix(cli/dev only): workaround to ignore "TypeError [ERR_INVALID_STATE]: Invalid state: Unable to enqueue"

- packages/waku/src/router/client.ts
https://github.com/wakujs/waku/pull/1408#issuecomment-2878255694
> fix(router/client): a workaround for canary-ci

- packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts
It's a leftover in #1281.
We need some tests to catch this. Would anyone like to contribute?
> fix(aws-lambda): remove errored code

- e2e/fixtures/monorepo/packages/waku-project/package.json
- e2e/utils.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts
From: https://github.com/wakujs/waku/pull/1393/files#r2092367853
> Oh, `waku: wakuPackageTgz`, is interesting.
I've refactored the overriding logic.
> chore(e2e): refactor e2e/utils.ts

- e2e/create-pages.spec.ts
- e2e/fixtures/create-pages/src/components/Counter.tsx
- e2e/fixtures/create-pages/src/components/funcs.ts
- packages/waku/src/minimal/client.ts
- packages/waku/src/router/client.ts
> fix: continue transition with server actions triggering rerender

- packages/waku/src/cli.ts
follow up #1407. Does it depend on nodejs version?
> fix(cli): ignore certain error in DEV

- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- packages/waku/tests/vite-plugin-fs-router-typegen.test.ts
> fix(typegen): routes with leading numbers cause typescript error

- packages/website/private/contents/post-010.mdx
issue called out here: https://bsky.app/profile/sebastienlorber.com/post/3lpovt4epa22m
by @slorber - thank you!
merging this to fix the post to avoid further confusion - happy to make changes again later if needed ofc
> fix(blog): page part example was wrong

- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- Close https://github.com/wakujs/waku/issues/1433
> chore: remove spaces in generated pages.gen.ts

- packages/website/private/contents/post-010.mdx
fixes comments from https://github.com/wakujs/waku/pull/1432
changing that in the first place was a result of me misreading the original example. I think this is fine and the comments are helpful. Let me know if there are other changes we want
> fix(blog): page part correction of correction

- e2e/fixtures/fs-router/src/pages/index.tsx
- e2e/fs-router.spec.ts
- packages/waku/src/minimal/client.ts
> fix: hydration mismatch

- packages/waku/package.json
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/renderers/html.ts
- pnpm-lock.yaml
> refactor: use html-react-parser

- e2e/examples-smoke.spec.ts
- e2e/hot-reload.spec.ts
- e2e/partial-build.spec.ts
- e2e/render-type.spec.ts
- e2e/utils.ts
- package.json
- playwright.config.ts
- pnpm-lock.yaml
Since https://github.com/wakujs/waku/pull/1470, we should allow parallelism.
> test: let `waku` auto find tcp port & enable parallelism

- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/create-pages.ts
- packages/waku/src/router/define-router.ts
- decode uri for SSR
- prefer decode uri to decode uri component
> refactor: decode uri for path

- e2e/define-router.spec.ts
- e2e/fixtures/define-router/src/components/slice001.tsx
- e2e/fixtures/define-router/src/routes/bar/page.tsx
- e2e/fixtures/define-router/src/routes/foo/page.tsx
- e2e/fixtures/define-router/src/routes/layout.tsx
- e2e/fixtures/define-router/src/routes/page.tsx
- e2e/fixtures/define-router/src/server-entry.tsx
- packages/waku/src/main.react-server.ts
- packages/waku/src/main.ts
- packages/waku/src/router/client.ts
- packages/waku/src/router/define-router.ts
> experimental: slice in define-router

- packages/waku/src/router/client.ts
- packages/waku/src/router/define-router.ts
> experimental: static/dynamic delayed slices

- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-transform.ts
- packages/waku/src/lib/renderers/html.ts
Extracted from https://github.com/wakujs/waku/pull/1493 as per https://github.com/wakujs/waku/pull/1493#discussion_r2182751499
> chore: internally export utils for Vite RSC

- packages/waku/src/cli.ts
- packages/waku/src/lib/builder/build.ts
- packages/waku/src/lib/builder/constants.ts
- packages/waku/src/lib/builder/platform-data.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-aws-lambda.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-cloudflare.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-deno.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-netlify.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-partykit.ts
- packages/waku/src/lib/plugins/vite-plugin-deploy-vercel.ts
- packages/waku/src/lib/plugins/vite-plugin-fs-router-typegen.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-entries.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-index.ts
- packages/waku/src/lib/plugins/vite-plugin-rsc-managed.ts
- packages/waku/src/lib/renderers/html.ts
following up #1460, just to make the code readable.
> refactor: rename SRC_MAIN and so on

- e2e/create-pages.spec.ts
- e2e/fixtures/create-pages/src/components/NoSsr.tsx
- e2e/fixtures/create-pages/src/components/OnlyClient.tsx
- e2e/fixtures/create-pages/src/server-entry.tsx
- packages/waku/src/lib/middleware/handler.ts
- packages/waku/src/lib/types.ts
- packages/waku/src/router/define-router.ts
> fix(define-router): unstable_disableSSR in createPages

- e2e/create-pages.spec.ts
- e2e/fixtures/create-pages/src/components/slice001.tsx
- e2e/fixtures/create-pages/src/components/slice002.tsx
- e2e/fixtures/create-pages/src/server-entry.tsx
- packages/waku/src/router/create-pages.ts
- packages/waku/tests/create-pages.test.ts
createSlice implementation with tests
> feat(create-pages): add createSlice to createPages api

- e2e/define-router.spec.ts
- e2e/fixtures/define-router/src/routes/baz/page.tsx
- packages/waku/src/router/client.ts
> fix(router): rename to lazy slices

- e2e/utils.ts
- packages/waku/src/lib/middleware/dev-server-impl.ts
otherwise, vite feature of auto reloading with polling doesn't work.
> fix(dev-server): prefer default ws port

- e2e/utils.ts
- package.json
- playwright.config.ts
Minor tweaks from https://github.com/wakujs/waku/pull/1493.
> test: minor tweaks (silence pnpm pack, add e2e-dev/prd scripts, adjust CI reporters)

- docs/create-pages.mdx
- docs/minimal-api.mdx
> fix(docs): rename to server-entry and client-entry

- e2e/fixtures/rsc-basic/index.html
- e2e/rsc-basic.spec.ts
This adds a test case for fallback index.html as discussed in https://github.com/wakujs/waku/pull/1493#discussion_r2247718780
> test: test index.html

- packages/waku/src/vite-rsc/plugin.ts
- Closes https://github.com/wakujs/waku/issues/1589
> fix: build serverless by default on VERCEL and NETLIFY

- e2e/fixtures/fs-router/src/pages/page-with-slices/index.tsx
- examples/11_fs-router/src/pages/_components/_slice-one.tsx
- examples/11_fs-router/src/pages/_components/_slice-two.tsx
- examples/11_fs-router/src/pages/slice-page.tsx
- packages/waku/src/router/fs-router.ts
> fix(slices): change slice prefix to remove _slice then any leading non-alphanumeric characters

- packages/waku/src/router/fs-router.ts
re https://github.com/wakujs/waku/pull/1592#issuecomment-3156893167
> refactor(fs-router): removeStart => removeSlicePrefix

- .github/workflows/e2e.yml
#1583 didn't work for windows.
> chore: fix e2e workflow

- tsconfig.eslint.json
Otherwise, I get out of memory error. Is this because of the latest tsc change?
> chore: tsconfig for eslint

- packages/waku/src/cli.ts
- packages/waku/src/lib/vite-rsc/cli.ts
- packages/waku/src/lib/vite-types.d.ts
> refactor: cli

- e2e/create-pages.spec.ts
- e2e/fixtures/create-pages/package.json
- packages/waku/src/lib/vite-rsc/build.ts
- packages/waku/src/lib/vite-rsc/plugin.ts
- packages/waku/src/lib/vite-rsc/ssr.tsx
- pnpm-lock.yaml
- Closes https://github.com/wakujs/waku/pull/1640
> fix: fix `handleBuild` with `"defaultHtml"`

- packages/website/waku.config.ts
There are too many files in `packages/website/dist/rsc/assets` due to each lazy loaded shiki language data. Since website is fully ssg-ed, server library can be externalized. Alternative is to use "Fine-grained Bundle" https://shiki.style/guide/bundles#fine-grained-bundle but that looks like more complicated.
<details><summary>Before</summary>
```
$ pnpm -C packages/website/ build
> waku-website@0.2.0 build /home/hiroshi/code/others/waku/packages/website
> waku build
vite v7.1.3 building SSR bundle for production...
✓ 923 modules transformed.
✓ built in 815ms
vite v7.1.3 building SSR bundle for production...
✓ 475 modules transformed.
✓ built in 305ms
vite v7.1.3 building SSR bundle for production...
✓ 923 modules transformed.
dist/rsc/assets/_layout-Dwf7IFU0.css …
```
> refactor(website): externalize `shiki` to reduce rsc build

- e2e/fixtures/fs-router/src/pages/_components/Counter.tsx
- e2e/fs-router.spec.ts
- packages/waku/src/router/client.ts
> fix: hydration error with useId

- packages/waku/src/lib/vite-rsc/ssr.tsx
- packages/waku/src/lib/vite-types.d.ts
- packages/waku/src/types.d.ts
Follow up to https://github.com/wakujs/waku/pull/1684#pullrequestreview-3204184252
> refactor: remove custom `react-dom/server.edge` types

- packages/waku/src/lib/builder/build.ts
> fix: add guard in emit static file
